- API.md
- README.md
- TERMS-OF-USE.md
- full-service/LICENSE
Adds a few relevant markdown files such as TERMS-OF-USE, API.md, and per-crate License file
> Add relevant markdown files

- full-service/src/bin/main.rs
- full-service/src/config.rs
- full-service/src/db/account.rs
- full-service/src/db/account_txo_status.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/mod.rs
- full-service/src/db/models.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/error.rs
- full-service/src/lib.rs
- full-service/src/service/decorated_types.rs
- full-service/src/service/mod.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/wallet.rs
- full-service/src/service/wallet_impl.rs
- full-service/src/test_utils.rs
> Update copyright 2021

- README.md
I tried to compile the full-service code and hit a few snags, so I added the fixes to the documentation.
> Documentation improvements.

- full-service/src/config.rs
- full-service/src/db/account.rs
- full-service/src/db/account_txo_status.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/models.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/error.rs
- full-service/src/service/decorated_types.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/wallet.rs
- full-service/src/service/wallet_impl.rs
- full-service/src/test_utils.rs
- rustfmt.toml
More consistent project formatting via rustfmt
> Add rustfmt.toml

- README.md
Added libssl to Ubuntu apt requirements.
Added instructions to install Brewfile on Mac.
> More tweaks to the README build instructions

- Cargo.lock
- Cargo.toml
- full-service/Cargo.toml
- full-service/src/bin/main.rs
- full-service/src/config.rs
- full-service/src/db/txo.rs
- full-service/src/error.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/wallet.rs
- full-service/src/service/wallet_impl.rs
- full-service/src/test_utils.rs
Soundtrack of this PR: [Queen & David Bowie: Under Pressure](https://www.youtube.com/watch?v=YoDh_gHDvkk)
The Fog Pubkey Resolver has been updated upstream, as well as Transaction Builder's usage of the Fog Pubkey Resolver. This PR uprevs to lastest upstream, and updates FogPubkeyResolver usage.
* Uprev mobilecoin submodule
* Update FogPubkeyResolver usage
[FS-89](https://mobilecoin.atlassian.net/browse/FS-89)
> FS-89: Uprev and Update Fog Resolver

- API.md
- README.md
Clean up and consistency of json objects in API.md and the README.md documentation of the json-rpc calls.
* Fixes to the API.md docs.
* Fixes to README.md docs.
[FS-94](https://mobilecoin.atlassian.net/browse/FS-94)
> Clean up json in API docs

- full-service/src/service/wallet.rs
Currently the end-to-end tests sleep to let the sync thread process the test ledger. This is sometimes flaky. There is a better way - this PR changes the tests to manually wait for the blocks to have synced.
* Adds `wait_for_sync` to end-to-end tests and replaces `thread::sleep` calls.
[FS-93](https://mobilecoin.atlassian.net/browse/FS-93)
> FS-93: Tests should manually sync not sleep

- README.md
- full-service/src/bin/main.rs
- full-service/src/config.rs
- full-service/src/db/transaction_log.rs
- full-service/src/error.rs
- full-service/src/service/decorated_types.rs
- full-service/src/service/wallet.rs
- full-service/src/service/wallet_impl.rs
- full-service/src/test_utils.rs
The plumbing for offline mode was missing a few pieces to make it work end-to-end. This PR finishes the plumbing for offline mode, and adds documentation to the README for how to use offline mode in a cold-wallet flow.
* Config plumbing for offline mode
* README updates for cold wallet flow
[FS-96](https://mobilecoin.atlassian.net/browse/FS-96)
> Fs 96: Offline config plumbing and documentation

- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/mod.rs
- full-service/src/db/models.rs
- full-service/src/db/txo.rs
The database layer is complex and would benefit from documentation.
* Adds doc comments to database entities.
* Adds doc comments to database access functions.
This is incremental progress, but since it's only comments I think we should merge early-and-often.
> Adds doc comments for database models and functions.

- full-service/migrations/2020-21-09-165203_wallet_service/up.sql
In #57, I thought I had committed a suggested change before merging, but it looks like the commit didn't take. This PR fixes the index for the finalized_block_index in up.sql.
* fixes finalized_block_index
> Fix index for finalized_block_index

- Cargo.lock
Regular submodule maintenance.
> Uprev Submodule

- API_v1.md
- API_v2.md
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/error.rs
- full-service/src/json_rpc/api_v1/decorated_types.rs
- full-service/src/json_rpc/api_v1/wallet_api.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/mod.rs
- full-service/src/json_rpc/txo.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/balance.rs
- full-service/src/service/mod.rs
- full-service/src/service/txo.rs
- full-service/src/service/wallet_service.rs
Soundtrack of this PR: [Social Network Soundtrack](https://www.youtube.com/watch?v=yydZbVoCbn0)
Continuing the refactor for API V2 with Txos.
* Add TxoService
* Update API V2
[FS-142](https://mobilecoin.atlassian.net/browse/FS-142)
> FS-142: Refactor Txos

- API_v1.md
- API_v2.md
- full-service/src/error.rs
- full-service/src/json_rpc/api_v1/decorated_types.rs
- full-service/src/json_rpc/api_v1/wallet_api.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/mod.rs
- full-service/src/json_rpc/proof.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/mod.rs
- full-service/src/service/proof.rs
- full-service/src/service/transaction_log.rs
- full-service/src/service/wallet_service.rs
Soundtrack of this PR: [Baby Shark](https://www.youtube.com/watch?v=j8z7UjET1Is)
Continuing the refactor of services and API.
* Refactors the proof service
[FS-159](https://mobilecoin.atlassian.net/browse/FS-159)
> FS-159: Refactor proofs

- hooks/pre-push
The old one wouldn't let us push to feature branches.
> Update pre-push hook for gitflow development process.

- API.md
- full-service/src/db/gift_code.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/gift_code.rs
Desktop wallet wants to show value of GiftCode while checking whether it is claimed.
* Changes check_gift_code_status to return the GiftCode as well as the status
* Adds "remove_gift_code"
* Updates "delete_account" to "remove_account"
[FS-172](https://mobilecoin.atlassian.net/browse/FS-172)
[FS-173](https://mobilecoin.atlassian.net/browse/FS-173)
> FS-172: Return GiftCode from check_status 

- full-service/src/db/account.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/balance.rs
- full-service/src/service/gift_code.rs
- full-service/src/test_utils.rs
> Allow import of accounts including fog fields.

- full-service/src/json_rpc/api_test_utils.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/transaction.rs
> Remove V2 language from the code. Remove redundant JSON response struct. Improve logging of requests in end-to-end tests.

- Cargo.lock
- full-service/src/config.rs
> Uprev mobilecoin submodule.

- full-service/src/db/txo.rs
- full-service/src/json_rpc/e2e.rs
https://mobilecoin.atlassian.net/browse/FS-163
> Fix FS-163, db crash after removing an account when it still has outlays in the system.

- full-service/src/db/account.rs
- full-service/src/db/account_txo_status.rs
- full-service/src/service/account.rs
WIP, unittest not passing yet.
> Remove AccountTxoStatus entries when an Account is removed.

- .gitignore
- API.md
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
close #86 
`build_transaction` returns `tx_proposal` and`TransactionID`
> `build_transaction` returns `tx_proposal` and`TransactionID` 

- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/txo.rs
> Removed force resyncing of account when assigning new subaddress

- full-service/src/json_rpc/wallet.rs
> add health check router

- API.md
Fixing an API documentation error
> Updated build gift code and checked the rest for consistency

- full-service/src/service/gift_code.rs
> handle invalid account id without crashing

- API.md
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/gift_code.rs
> Add memo to the output of check_gift_code_status.

- full-service/src/json_rpc/gift_code.rs
- full-service/src/json_rpc/txo.rs
> Missed one when converting names to txo_id_hex.

- Cargo.lock
- full-service/Cargo.toml
- full-service/src/bin/main.rs
- full-service/src/config.rs
According to the [TERMS-OF-USE](https://github.com/mobilecoinofficial/full-service/blob/main/TERMS-OF-USE.md):
> Purchasers of MobileCoins may not transact, transfers, or trade MobileCoins in the United States or with U.S. Persons or entities, or persons or entities present in the United States.
This PR adds a check to disable full-service in IPs originating from the US.
* Adds IP check in full-service config
> Add IP Check

- API.md
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/receipt.rs
- full-service/src/service/transaction.rs
- full-service/src/service/txo.rs
> Remove first_block_index from the create_account endpoint.

- API.md
- full-service/src/json_rpc/account_secrets.rs
- full-service/src/json_rpc/e2e.rs
> 🚑  allowing export of legacy account secrets

- API.md
- full-service/src/db/account_txo_status.rs
- full-service/src/json_rpc/e2e.rs
Cleans up leftover print statements and fixes link in API.md
> 🎨 Clean up print statements and fix link

- full-service/src/service/account.rs
> Do not crash the server when an invalid mnemonic is passed.

- API.md
- full-service/src/db/account.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/address.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/transaction_log.rs
- full-service/src/json_rpc/txo.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/address.rs
- full-service/src/service/receipt.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/transaction_log.rs
- full-service/src/service/txo.rs
- full-service/src/test_utils.rs
Add limit and offset parameters to these RPC calls:
* get_all_txos_for_account
* get_all_transaction_logs_for_account
* get_all_addresses_for_account
> Add pagination.

- API.md
> Update docs for name change of get_block_object -> get_block.

- full-service/src/json_rpc/e2e.rs
Fix intermittent failures of wait-for-sync during complex end-to-end
tests.
> Fix flaky tests.

- full-service/src/db/account_txo_status.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/txo.rs
- full-service/src/db/wallet_db_error.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/service/address.rs
- full-service/src/service/ledger.rs
txos were being marked as unspent when coming from a state of orphaned
* Fixed FS-195
* None
> [FS-195] - Feature/bugfix/all txos marked unspent

- Cargo.lock
- full-service/Cargo.toml
- full-service/src/json_rpc/network_status.rs
- full-service/src/service/balance.rs
- full-service/src/service/ledger.rs
- full-service/src/service/transaction.rs
- Add network fee to network_status endpoint.
- Use dynamic fees when building transactions.
> Dynamic fees

- full-service/src/bin/main.rs
- full-service/src/config.rs
> Block IP addresses in OFAC sanctioned countries.

- full-service/src/db/account.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/e2e.rs
> Scrub unreferenced Txos from the database when an account is deleted.

- cli/.gitignore
- cli/README.md
- cli/bin/mobcli
- cli/mc_env.sh
- cli/mobilecoin/__init__.py
- cli/mobilecoin/cli.py
- cli/mobilecoin/client.py
- cli/mobilecoin/utility.py
- cli/setup.py
- cli/test/client_tests.py
> Add python cli to main repo, to avoid version conflicts.

- full-service/src/json_rpc/api_test_utils.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
> Update error reporting format to match JSON-RPC 2.0 spec.

- cli/mobilecoin/cli.py
- cli/test/test_display.py
> Fix decimal formatting of amounts less than 0.0001.

- README.md
- full-service/src/config.rs
> Make gitbook page easier to find. Fix a comment.

- README.md
> Fix an oversight in README for Ubuntu apt installation.

- full-service/src/service/ledger.rs
> Use a fallback fee of 10mMOB, instead of 400μMOB.

- README.md
- full-service/src/config.rs
- full-service/src/service/ledger.rs
- full-service/src/service/transaction_builder.rs
> Release/v1.0.0 pre.7

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- full-service/Cargo.toml
> Uprev 2021 06 25

- .circleci/config.yml
Trying to speed up CI by caching develop build artifcats
> Ci cache develop

- cli/mobilecoin/printable_pb2.py
- cli/mobilecoin/utility.py
- cli/setup.py
Hack around Python imports and add missing dependencies so that the Python lib is pip-installable
> Py module fixes

- full-service/src/config.rs
In this PR
Pull in ToS changes from master.
Update IP blocking to match the ToS.
> removed US IP block

- cli/mobilecoin/cli.py
Add a CLI option to generate receipts.
Fix off-by-one errors when setting tombstone block. Let full-service daemon set the default tombstone block for newly generated transactions.
> Generate receipts from CLI

- cli/mobilecoin/cli.py
> No need to use segno fork anymore.

- CONTRIBUTING.md
- README.md
- full-service/src/db/models.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/transaction_log.rs
While performing some stress testing, I wanted to clean up some tests, fix some functionality, and improve the documentation.
* Update README to include ingest-enclave.css in the build and run, and feature the gitbook documentation more prominently. Also added a Table of Contents
* Addressed a FIXME in the log_submitted test to verify the change was correctly updated after scanning the submitted block
* Added a test for submitting a transaction log for a transaction > i64::max, and fixed the code to properly process this transaction log
Fixes: https://app.asana.com/0/1200175610892874/1201322031072225/f
* Working to update the mobilecoin submodule
* Continue sniping FIXMEs
> Tests and fixes

- full-service/src/service/balance.rs
> Fix an off-by-one error calculating account_block_height for balances.

- cli/mobilecoin/cli.py
> Improve help when incorrectly typing "mobcli address".

- cli/mobilecoin/cli.py
> We should be showing the change subaddress in mobcli address list.

- cli/mobilecoin/cli.py
> Show orphaned txos in CLI account list.

- cli/mobilecoin/cli.py
- cli/mobilecoin/client.py
> Implement fees correctly in mobcli.

- full-service/src/db/account.rs
- full-service/src/db/wallet_db.rs
> Enable foreign key constraints. Fix transient FK errors when deleting an account.

- full-service/src/db/account.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/transaction_log.rs
- full-service/src/json_rpc/txo.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/receipt.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/txo.rs
- full-service/src/test_utils.rs
> Fix the handling of txos in the range of 2^63 to 2^64 pmob. Refactor usage of i64 and u64 values.

- full-service/src/db/assigned_subaddress.rs
in order to make full service compatible with https://github.com/mobilecoinfoundation/mobilecoin/pull/1649#pullrequestreview-913416927
> Remove reference to viewkey

- docs/README.md
- docs/tutorials/environment-setup.md
Add links to tutorials on gitbook landing page
> Improve gitbook landing page

- cli/mobilecoin/cli.py
> Show commit hash in "mobcli version" command.

- full-service/src/config.rs
> Fix broken migration attempt on empty LMDB.

- cli/mobilecoin/cli.py
- cli/mobilecoin/client.py
- full-service/src/bin/transaction-signer.rs
- full-service/src/db/transaction_log.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/transaction.rs
> Implement CLI for unified accounts. Improve naming of offline tx-proposal files.

- Cargo.lock
- full-service/Cargo.toml
- full-service/src/bin/main.rs
- full-service/src/bin/transaction-signer.rs
- full-service/src/config.rs
- full-service/src/db/account.rs
- full-service/src/json_rpc/account_key.rs
- full-service/src/json_rpc/block.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/receiver_receipt.rs
- full-service/src/json_rpc/unspent_tx_out.rs
- full-service/src/service/balance.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/ledger.rs
- full-service/src/service/receipt.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/test_utils.rs
- full-service/src/unsigned_tx.rs
- full-service/src/validator_ledger_sync.rs
- validator/connection/Cargo.toml
- validator/connection/src/lib.rs
- validator/service/src/bin/main.rs
> Uprev the mobilecoin submodule to version 1.3.

- docs/dbdocs/database.dbml
- full-service/migrations/2022-06-13-204000_api_v3/up.sql
- full-service/src/db/account.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/models.rs
- full-service/src/db/schema.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/db/wallet_db_error.rs
- full-service/src/json_rpc/e2e_tests/account/account_address.rs
- full-service/src/json_rpc/e2e_tests/account/account_other.rs
- full-service/src/json_rpc/e2e_tests/transaction/build_submit/build_then_submit.rs
- full-service/src/json_rpc/e2e_tests/transaction/build_submit/multiple_outlay.rs
- full-service/src/json_rpc/e2e_tests/transaction/transaction_txo.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/transaction_log.rs
- full-service/src/json_rpc/txo.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/balance.rs
- full-service/src/service/confirmation_number.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/receipt.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/txo.rs
- full-service/src/test_utils.rs
The goal is to decrease the complexity of and normalize the database. This tackles the txos table, and how we determine the status of a given TXO.
* Refactored txos table
* Refactored transaction_txos table into transaction_input_txos and transaction_output_txos
* Refactored how to determine status of txos
* continued refactoring of tables and code in preparation of support multiple token ids
> Refactor Txos

- full-service/src/bin/transaction-signer.rs
as per request from @holtzman for a way to create an import package and backup file from an existing mnemonic
> Add import to transaction signer for existing mnemonic

- full-service/src/service/gift_code.rs
Using the network block version instead of the BlockVersion::MAX
> Claim Gift Code fix

- Dockerfile
Soundtrack of this PR: [A change is gonna come](https://www.youtube.com/watch?v=fPr3yvkHYsE)
The `full-service` binary was updated to `mc-full-service`.  This PR changes the references in the `Dockerfile` and makes a symlink for backward compatibility.
* Dockerfile update for `mc-full-service`
* None planned.
> Update Dockerfile to use new binary name and symlink to old binary name

- full-service/src/service/balance.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/ledger.rs
- full-service/src/service/transaction.rs
- validator/service/src/blockchain_api.rs
This is a cherry pick of #502 to the release branch for 1.9.5
> Fix issues surfaced by block version 2 (#502)

- README.md
XCode versions are confusing in the README
* Updated unsupported XCode versions
> Update README for unsupported xcode versions

- .github/workflows/ci.yml
- cli/forest_utils.py
- cli/fullservice.py
- cli/pyproject.toml
Quick little quality of life improvement: This makes the response from FS much more readable in the Python Library, using the fantastic [rich](https://pypi.org/project/rich/) library.
> prettyprint the response from full service

- integ-tests/basic.py
We need to wait for the ledger to sync before trying to run the test.
> wait for ledger to sync

- integ-tests/basic.py
> Fix argparse in basic.py 

- .internal-ci/docker/entrypoints/full-service.sh
Fix entrypoint script so cli arguments work.
> fix: fix entrypoint script for compatiblity with cli arguments

- python-library/fullservice.py
Clearer understanding of how to interact with important parts of the library, making development easier in the short and long term. 
Typing for request functions, build transaction, submit transaction, account status, network status, wallet status and import account. 
* [Typing for the rest of the library ( as well as tests ) ](https://www.pivotaltracker.com/story/show/183798426)
> Partial typing for parts of the python library

- python-library/create_account_test.py
Simple test that gets the number of accounts, creates one, and checks to make sure the number of accounts increased.
* [We will have to orchestrate the entire test suite as a whole. ](https://www.pivotaltracker.com/story/show/183966740)
> Simple test for create_account

- .internal-ci/test/fs-integration/basic.py
Quick hack to add pytest compatibility to `basic.py` as is from my refactored branch.
> pytest for main test 

- docs/v2/api-endpoints/get_transaction_log.md
- docs/v2/api-endpoints/get_transaction_logs.md
- docs/v2/transactions/transaction-log/README.md
Fixing some incorrect docs for transaction log endpoints
> fixing incorrect docs for v2 get_transaction_log(s)

- docs/tutorials/environment-setup.md
- docs/tutorials/resolve-disputes.md
- docs/v2/api-endpoints/build_and_submit_transaction.md
- docs/v2/api-endpoints/sample_mixins.md
< How to run the unit test, e2e test etc. >
< Or what are the actual request/response might look like (like grpcurl) >
> Document updates

- docs/tutorials/resolve-disputes.md
- docs/v1/api-endpoints/get_balance_for_address.md
- docs/v1/api-endpoints/version.md
- docs/v2/api-endpoints/get_address_status.md
- docs/v2/api-endpoints/version.md
- full-service/src/json_rpc/v2/e2e_tests/account/account_balance.rs
- mirror/test/run.sh
- mirror/test/test_suite/test_script.js
- python/mobilecoin/client.py
- python/tests/stress.py
> Remove api_version from JSON requests, as it is no longer used.

- full-service/src/json_rpc/v1/api/wallet.rs
- full-service/src/json_rpc/v2/api/wallet.rs
This is needed to better identify errors that are reported to the API that aren't currently reported in the logs. This only reports the outcome and any error that comes back with it.
* Added logging to API response
> adding info logging for command success and failure message

- full-service/src/db/txo.rs
- full-service/src/json_rpc/v1/models/txo.rs
- full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/build_then_submit.rs
- full-service/src/service/balance.rs
- tools/build-fs.sh
- tools/run-fs.sh
- tools/test.sh
Reverts mobilecoinofficial/full-service#692
> Revert "Feat/reintroduce secreted status"

- tools/rustdoc.sh
> Write a script to compile rustdocs.

- mirror/src/private/main.rs
The same as #718 but for main branch, which will be cherry picked into any release branches already in existence once merged.
> adding the collection of v1 endpoints to mirror allowed endpoints

- mirror/EXAMPLE.md
- mirror/README.md
Trying to improve readability
* Updates to the mirror node docs
> Doing some README cleanup

- CONTRIBUTING.md
- README.md
> Improve documentation. Add correct commands for running from docker. Remove out of date cold-wallet flow instructions.

- .github/workflows/dev-cd.yaml
- python/mobilecoin/client.py
- tools/.shared-functions.sh
- tools/build-fs.sh
- tools/run-fs.sh
< How to run the unit test, e2e test etc. >
< Or what are the actual request/response might look like (like grpcurl) >
> setting git config global safe directory

- .github/workflows/release.yml
- python/tests/test_client.py
We have OSX runners again & we need to release the OSX builds
- Do a release
- make sure files appear
> readding osx to release CD

- python/tests/test_client.py
- tools/build-fs.sh
- tools/run-fs.sh
Integration test sort was ordered incorrectly
Also updating some build/run script stuff
> Fixing integration tes

- .gitignore
> Add mobilecoin_secret_*_.json files to the gitignore.

- README.md
> Fix table of contents in README, it was out of date.

- .github/workflows/release.yml
> Change release action to put tar packaged files in a folder.

- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/gift_code.rs
- full-service/src/db/transaction_log.rs
Motivation
Use rust doc to enhance documentations of full service
In this PR
Add inline arguments for all modules in mc_full_service::db except `txo`
Test Plan
Documentations change only. Need manual test or view
Future Work
Add rust doc for `txo` module in mc_full_service::db
> Rustdoc models continued

- tools/.shared-functions.sh
- tools/run-fs.sh
> Improve error reporting in run-fs.sh when --validator is enabled.

- python/mobilecoin/client.py
- python/mobilecoin/client_v1.py
- python/tests/conftest.py
- python/tests/test_client.py
> Add X-API-KEY header into requests from Python API.

- .github/workflows/dev-cd.yaml
- python/mobilecoin/cli.py
- python/mobilecoin/client.py
- python/mobilecoin/client_v1.py
> Split full-service url config in CLI into host and port. Update integration test configuration.

- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/txo.rs
Motivation
Use rust doc to enhance documentations of full service
In this PR
Add inline arguments for mc_full_service::db except txo
Test Plan
Documentations change only. Need manual test or view
> Finish Rustdoc for txo model

- README.md
> Improve build and run instructions for Arch Linux.

- SUMMARY.md
- usage/logging/README.md
- usage/logging/crash-reports.md
- usage/logging/text-logs.md
Add basic instructions for log file(s)/debugging
Add basic instructions for log file(s)/debugging
fixes #184165799
Documentation update, no test needed.
> 184165799 add basic instructions for log file(s)/debugging

- Cargo.lock
> bump mc to v5.0.0-pre.1

- python/mobilecoin/client_v1.py
> fix broken url construction in test_client_v1.py

- full-service/src/db/account.rs
- full-service/src/json_rpc/v2/models/account_key.rs
- full-service/src/util/encoding_helpers.rs
> Make export_secrets endpoint encode fog_authority_spki as base64, not hex.

- full-service/src/db/txo.rs
> add account filter when querying for txos at account

- full-service/src/json_rpc/v1/api/wallet.rs
- python/mobilecoin/client.py
- python/mobilecoin/client_v1.py
> Allow getting transaction logs by txo_id in the v1 api for get_transaction_log.

- Cargo.lock
- Cargo.toml
> update to mc 5.0.8

- .github/workflows/ci.yml
- .github/workflows/dev-cd.yaml
- .github/workflows/dev-delete-cd.yaml
- tools/build-fs.sh
Updating CI to fix a build failure
Removing some checks that have been failing that we have been ignoring. Will need help to fix, as it's related to helm/deploy stuff.
> Fixing CI and disabling some checks

- t3/api/src/lib.rs
Default port was incorrectly set to 80 before, it should be 443
> update default secure port to 443 for T3 URI

- full-service/src/service/memo.rs
validate_sender_memo currently always returns false because it is using the recipient's base view private key to recreate the memo's HMAC for matching against the one stored in the memo. Instead, the subaddress view private key for the subaddress that received the txo should be used.
This PR adds looking up the subaddress index for the address which received the txo and using it to pass the recipient's subaddress view private key to the authenticated memo validator.
It also adds a new internal error in case the txo is orphaned (no subaddress index for the txo in the walletdb) which could happen if the account is imported after having been used elsewhere and insufficient subaddress indexes to cover all of the previously assigned addresses were initialized.  We consider this an error rather …
> validate sender memo using recipient subaddress

- .github/CODEOWNERS
Add to people who's PR approval allow merging into main
> add additional codeowners

- Cargo.lock
- full-service/Cargo.toml
- mirror/Cargo.toml
- signer/Cargo.toml
- t3/api/Cargo.toml
- t3/connection/Cargo.toml
- validator/api/Cargo.toml
- validator/connection/Cargo.toml
- validator/service/Cargo.toml
bump version to v2.10.1 in preparation for release
> bump version to 2.10.1

- .github/workflows/build.yml
Update build.yaml to use our new gha runners.
> update gha runners in build

- full-service/src/config.rs
The help text for --deposits-webhook-url is updated to match the latest behavior
> update help for --deposits-webhook-url

- Cargo.lock
- full-service/Cargo.toml
- mirror/Cargo.toml
- signer/Cargo.toml
- t3/api/Cargo.toml
- t3/connection/Cargo.toml
- validator/api/Cargo.toml
- validator/connection/Cargo.toml
- validator/service/Cargo.toml
in preparation for release, bump version to 2.10.3
* bumps version to 2.10.3
> bump version to 2.10.3

- Cargo.lock
- full-service/Cargo.toml
- mirror/Cargo.toml
- signer/Cargo.toml
- t3/api/Cargo.toml
- t3/connection/Cargo.toml
- validator/api/Cargo.toml
- validator/connection/Cargo.toml
- validator/service/Cargo.toml
Update version strings in preparation for release v2.10.4
> bump version to 2.10.4

- .github/actionlint.yaml
- .github/actions/build-docker/action.yaml
- .github/actions/publish-docker/action.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/on-tag.yaml
Update builds to produce Linux ARM64 binaries and Docker Image artifacts.
> add arm64 linux build

- .github/workflows/on-pr.yaml
- .mobconf
- tools/.shared-functions.sh
- tools/build-fs.sh
- tools/build-signer.sh
- tools/install_git_settings.sh
- tools/lint-fix.sh
- tools/lint.sh
- tools/mirror/run-full-service.sh
- tools/mirror/run-mirror-private.sh
- tools/mirror/run-mirror-public.sh
- tools/mirror/run-validator.sh
- tools/protobuf_update.sh
- tools/run-fs.sh
- tools/rustdoc.sh
- tools/test-with-coverage.sh
- tools/test.sh
- update mob prompt to use mobilecoin/fat-builder image.
- refactor scrips in tools/ for consistency and pass shellcheck
> Update build tools

- .github/workflows/refresh-ledger.yaml
Adds task to upload refreshed ledger to Central US datacenter.
> update refresh job to upload ledger to us datacenter

- Cargo.lock
- full-service/Cargo.toml
- mirror/Cargo.toml
- signer/Cargo.toml
- t3/api/Cargo.toml
- t3/connection/Cargo.toml
- validator/api/Cargo.toml
- validator/connection/Cargo.toml
- validator/service/Cargo.toml
prepare for a new release
* bump version strings
> bump version to 2.10.5

- .github/workflows/on-tag.yaml
* fix another typo in on-tag github action
> fix another typo in on-tag github action

- .github/workflows/refresh-ledger.yaml
Fix the ledger refresh job.  
- Update script to use new release artifact name.
- Add slack alert for job failure.
Trigger test job from branch
> fix tarball name for ledger refresh
