mobilecoinofficial/full-service

- API.md
- Cargo.lock
- README.md
- full-service/Cargo.toml
- full-service/src/error.rs
- full-service/src/service/decorated_types.rs
- full-service/src/service/wallet.rs
- full-service/src/service/wallet_impl.rs
We needed to document the `verify_proofs` endpoint, and in the process, I realized we needed a convenience call to `get_proofs` for a transaction.
* Uprevs mobilecoin
* Adds `get_proofs`
* Documents the proof object in the API doc, as well as the proof service methods in the README.
[WS-52](https://mobilecoin.atlassian.net/browse/WS-52)
> Get Proofs and Proof Documentation

- full-service/src/config.rs
- full-service/src/service/decorated_types.rs
- full-service/src/service/wallet.rs
Soundtrack of this PR: [Undone](https://www.youtube.com/watch?v=LHQqqM5sr7g)
The JsonTxProposal object has several u64s in various objects contained therein. This change introduces a StringifiedJsonTxProposal which has all internal u64s represented as strings.
* StringifiedJsonTxProposal and StringifiedUnspentTxOut
[WS-78](https://mobilecoin.atlassian.net/browse/WS-78)
> WS-78: TxProposal Stringify

- full-service/src/error.rs
- full-service/src/service/wallet.rs
The current error formatting is clunky and doesn't guarantee proper json. This PR fixes that.
* Introduces format_error helper at jsom-rpc layer
* Fixes up displaydoc for errors to add `:` before wrapped error.
[FS-92](https://mobilecoin.atlassian.net/browse/FS-92)
> FS-92: JSON Errors

- full-service/src/db/models.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
New model types should take &[u8] rather than &Vec.
* Modifies new models specification to take &[u8] rather than &Vec
[FS-98](https://mobilecoin.atlassian.net/browse/FS-98)
> FS-98: New models take &[u8] rather than &Vec

- Cargo.lock
- full-service/src/config.rs
- full-service/src/service/wallet.rs
- full-service/src/test_utils.rs
A previous oversight left the submodule at a revision from my fork, rather than from mobilecoin's master. This PR uprevs mobilecoin submodule to latest, which includes adding the new credentials provider to the ThickClient.
* uprevs mobilecoin
* adds HardcodedCredentialsProvider to ThickClient usage
> Uprev mobilecoin and Add Credentials Provider

- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/error.rs
- full-service/src/service/decorated_types.rs
- full-service/src/service/sync.rs
- full-service/src/test_utils.rs
The current Txo processing did not account well for the case where an account is sending transactions to itself. This PR fixes that case, and updates the txo lifecycle test to be more complete.
* Addresses pay-to-self edge case for Txo processing
* Updates `test_txo_lifecycle` to account for this case
* Adds a `list_txo_by_type` method in the Txo db crate. We may expose this in the future at the API level, but for now it's only used in the test.
[FS-99](https://mobilecoin.atlassian.net/browse/FS-99)
> FS-99: Address pay-self edge case and test

- full-service/src/db/b58.rs
- full-service/src/db/mod.rs
This is an extract of https://github.com/mobilecoinofficial/full-service/pull/24. I am breaking that into smaller independent PRs so that they are easier to review and merge.
- Handles a few errors instead of calling `unwrap()`,
- Moves b58 encoding into a separate file. That just feels nicer to me than cluttering up mod.rs,
- Stubs out a few unit tests. I'd like to work on those later.
> Moves b58 encoding to a separate file, and stubs out a few unit tests

- full-service/src/db/account.rs
- full-service/src/db/account_txo_status.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/mod.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/db/wallet_db.rs
- full-service/src/db/wallet_db_error.rs
- full-service/src/error.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction_builder.rs
This change is pulled from https://github.com/mobilecoinofficial/full-service/pull/24
- Moves WalletDb out of mod.rs. That feels clean to me, and ought to help with organization if we do things like use a trait and/or mocks for this.
- Moves WalletDbError out of the top-level errors.rs, into a separate file under `db`. Small files feel better to me, and I like keeping error types close to the code that generates those errors.
> Moves WalletDb and WalletDbError to separate files under db

- full-service/src/db/account.rs
- full-service/src/db/account_txo_status.rs
- full-service/src/db/models.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/wallet.rs
- full-service/src/service/wallet_impl.rs
- full-service/src/test_utils.rs
This folds together the previous PRs that updated the DB constants' names and values. Those were small PRs, so it seemed easier to review them as a bunch instead of rebasing each of them on top of the latest changes.
* Updates names of constants to more clearly indicate what they are used for ("foo_status", "foo_type", etc)
* Updates values of constants to match the constant names. 
* Fixes a few unit tests that accidentally referred to DB constants instead of JSON response fields.
> Db constants

- API_v2.md
- full-service/migrations/2020-21-09-165203_wallet_service/up.sql
- full-service/src/db/account.rs
- full-service/src/db/models.rs
- full-service/src/db/schema.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/db/wallet_db_error.rs
- full-service/src/json_rpc/account.rs
- full-service/src/json_rpc/account_key.rs
- full-service/src/json_rpc/account_secrets.rs
- full-service/src/json_rpc/api_test_utils.rs
- full-service/src/json_rpc/api_v1/decorated_types.rs
- full-service/src/json_rpc/api_v1/wallet_api.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/mod.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/json_rpc/wallet_status.rs
- full-service/src/service/account.rs
- full-service/src/service/balance.rs
- full-service/src/service/wallet_service.rs
- full-service/src/test_utils.rs
Users need a way to be able to export their account secrets. There should also be a way to import an account from an account key.
* adds account key secret export
* adds import by account key
* moves entropy to be a nullable field for the Account object (in case you import an account key)
* adds tests
* updates documentation
* removes tests and endpoints from api_v1 that are now deprecated.
* I think this also fixes the flaky test
[FS-64](https://mobilecoin.atlassian.net/browse/FS-64)
[FS-57](https://mobilecoin.atlassian.net/browse/FS-57)
[FS-125](https://mobilecoin.atlassian.net/browse/FS-125)
> FS-64: Export Account Secrets

- API_v2.md
- full-service/migrations/2020-21-09-165203_wallet_service/up.sql
- full-service/src/db/transaction_log.rs
- full-service/src/json_rpc/api_test_utils.rs
- full-service/src/json_rpc/api_v1/decorated_types.rs
- full-service/src/json_rpc/api_v1/wallet_api.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/transaction_log.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/balance.rs
- full-service/src/service/mod.rs
- full-service/src/service/transaction_log.rs
- full-service/src/service/wallet_service.rs
- full-service/src/test_utils.rs
It is desirable to be able to get transactions by block number. This PR adds two API endpoints related to transaction_logs and block indices: 
* `get_all_transaction_logs_by_block`: Gets all transaction logs associated with a specific block index.
* `get_all_transaction_logs_ordered_by_block`: Gets all transaction logs, and orders them by `finalized_block_index`
* Continues the refactor for API v2 and moves `transaction_log` related service methods to a `TransactionService` trait.
* Adds two API endpoints for getting transaction_logs associated with a block
[FS-114](https://mobilecoin.atlassian.net/browse/FS-114)
Also cleans up transaction_log naming to make it consistent, for [FS-72](https://mobilecoin.atlassian.net/browse/FS-72)
Note: This PR is built on top of #56, so will be rebased …
> FS-114: Transactions by Block

- API_v2.md
We added the export_account_secrets endpoint in #58, but the documentation was missing from the API_v2.md. This PR adds the documentation for the endpoint.
* adds docu for export_account_secrets
> Add documentation for export account secrets

- API_v2.md
- Cargo.lock
- full-service/Cargo.toml
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/address.rs
- full-service/src/service/transaction.rs
Soundtrack of this PR: [Marty O'Reilly & The Old Soul Orchestra](https://www.youtube.com/watch?v=lpIR4HCwlq0&list=PLZDAtvNZpqDGXDHI_ZEioFAaKce9jsIYH&index=4)
We should verify addresses, particularly before sending to them
* Adds verify_address endpoint and tests
* Updates build_transaction to verify_address, and adds a test
[FS-143](https://mobilecoin.atlassian.net/browse/FS-143)
[FS-157](https://mobilecoin.atlassian.net/browse/FS-157)
> FS-143: Verify public address

- API_v2.md
- full-service/src/error.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/address.rs
- full-service/src/service/balance.rs
- full-service/src/service/ledger.rs
- full-service/src/service/mod.rs
- full-service/src/service/transaction.rs
- full-service/src/service/wallet_service.rs
Soundtrack of this PR: [MobileCoin Radio: Graham Patzner](https://www.youtube.com/watch?v=j5ufaau-l34&list=PLZDAtvNZpqDGXDHI_ZEioFAaKce9jsIYH&index=3)
The balance for a subaddress may be useful for determining the value that has been received or spent from an existing subaddress.
* Adds `get_balance_for_address`
* Refactors the `get_network_block_index` to a new `LedgerService`. This service will also hold all the `get_ledger_object` calls, but that will be in a future PR.
[FS-106](https://mobilecoin.atlassian.net/browse/FS-106)
> FS-106: Get balance for address

- API.md
- full-service/migrations/2021-03-07-192850_receipts/down.sql
- full-service/migrations/2021-03-07-192850_receipts/up.sql
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/mod.rs
- full-service/src/json_rpc/receiver_receipt.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/mod.rs
- full-service/src/service/proof.rs
- full-service/src/service/receipt.rs
- full-service/src/service/transaction.rs
- full-service/src/service/txo.rs
A primitive in the MobileCoin system is the "Receiver Receipt," where a recipient can be handed a "Receiver Receipt" from the sender, and they can use the data in this receipt to poll for the Txos in the transaction, and the verify the proof that the Txo was associated with the Receipt, implying that whoever is providing the receipt constructed the transaction.
* Adds a ReceiptService
* Implements `check_receiver_receipt_status` and `create_receiver_receipt`
* Implements `Txo::select_by_public_key` to select the Txos from the receipt
* Adds tests at each layer
[FS-95](https://mobilecoin.atlassian.net/browse/FS-95)
* Explore other convenience endpoints based on feedback from merchant services prototypes
> FS-95: Receipts

- API.md
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/amount.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/mod.rs
- full-service/src/json_rpc/receiver_receipt.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/receipt.rs
The `check_receipt_status` endpoint was not quite right to meet the needs of receipt verification.
* Uses `mc_api::external.Receipt` as opposed to `mobilecoind_api::ReceiverReceipt`
* Returns Txo along with status
* Verifies on address as opposed to account
* Updates API docs
[FS-174](https://mobilecoin.atlassian.net/browse/FS-174)
> FS-174: Improve Receipt API

- full-service/src/bin/main.rs
- full-service/src/config.rs
- full-service/src/db/txo.rs
- full-service/src/db/wallet_db.rs
- full-service/src/json_rpc/api_test_utils.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction.rs
- full-service/src/service/txo.rs
- full-service/src/test_utils.rs
Soundtrack of this PR: [Yo-Yo Ma: Hush Little Baby](https://www.youtube.com/watch?v=UTstU-st-7o)
Currently, the max db connections are set at 1, to avoid `database is locked` errors from SQLite. This PR makes some configuration changes and app-level changes to gracefully retry when database is locked.
* Enable WAL
* Gracefully requeue account if syncing fails due to database locked (this also fixes when the sync thread appeared to die and not recover)
* Remove sleeping from tests (except when in the controlled `wait_for_sync` method
[FS-162](https://mobilecoin.atlassian.net/browse/FS-162)
[FS-121](https://mobilecoin.atlassian.net/browse/FS-121)
[FS-156](https://mobilecoin.atlassian.net/browse/FS-156)
> Handle database-is-locked more gracefully

- full-service/src/db/txo.rs
This is related to the previous pull request about AccountTxoStatus
> Do not crash in Txo::get if there is an AccountTxoStatus referring to a nonexistent account.

- full-service/src/db/txo.rs
This query was suspiciously returning too many Txos.
> Fix a query to get txos for a particular address.

- full-service/src/service/sync.rs
Move Database is locked "warn" message to "trace"
> Trace database locked log message

- API.md
- full-service/src/db/account.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/balance.rs
- full-service/src/test_utils.rs
Users should be able to dictate their known next subaddress index when importing an account. This will be a small usability fix before the larger recovery feature is designed and implemented.
* Larger recovery mode features
> ✨ 📝 ✅  Added field for next subaddress index to import_account

- API.md
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
We renamed txo_id -> txo_id_hex everywhere internally, but at the json_rpc layer, it should be txo_id.
* Renames txo_id_hex -> txo_id at the API layer.
> txo_id_hex -> txo_id at json_rpc layer

- API.md
- Cargo.lock
- full-service/Cargo.toml
- full-service/migrations/2021-03-30-021521_slip10_account_key/down.sql
- full-service/migrations/2021-03-30-021521_slip10_account_key/up.sql
- full-service/migrations/2021-03-30-143827_key_derivation_version/down.sql
- full-service/migrations/2021-03-30-143827_key_derivation_version/up.sql
- full-service/src/db/account.rs
- full-service/src/db/models.rs
- full-service/src/db/schema.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/account.rs
- full-service/src/json_rpc/account_secrets.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/test_utils.rs
* Support new SLIP0010 key derivation path.
* Implement this work: https://github.com/mobilecoinfoundation/mobilecoin/pull/776
* Turn root entropy into a legacy system.
* Support new key derivation path for account create, import, and export.
* Only support old key derivation path for import.
> Support SLIP0010 key derivation path from mnemonic

- full-service/src/json_rpc/account.rs
- full-service/src/json_rpc/address.rs
- full-service/src/json_rpc/balance.rs
- full-service/src/json_rpc/transaction_log.rs
- full-service/src/json_rpc/txo.rs
- full-service/src/service/balance.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction.rs
- full-service/src/service/txo.rs
When investigating the origin block for an upcoming blog post, it became apparent that the jsonrpc layer was not displaying the value correct for a large u64. This PR fixes that.
* casts the DB's i64 to u64 before displaying
* Adds tests for sync and jsonrpc display of txo
> Display u64 in Origin Block

- full-service/src/db/account.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/e2e.rs
Soundtrack of this PR: [https://www.youtube.com/watch?v=VuNIsY6JdUw](You Belong With Me)
When assigning an new subaddress, we always want to check to see if there are any orphaned txos that belong to it.
* see above.
* A full recovery mode
> Assigning Next Subaddress Now Checks For Any Owned Orphaned TXOs

- full-service/src/db/assigned_subaddress.rs
- full-service/src/service/address.rs
Quick fix for bug with transaction logs assigned subaddress index not updating when an orphaned txo was claimed by a subaddress
> Updated Assigned Subaddress B58 of transaction log when orphaned TXO is picked up by a subaddress

- Cargo.lock
- full-service/migrations/2021-04-20-182449_gift_code_two_entropies/down.sql
- full-service/migrations/2021-04-20-182449_gift_code_two_entropies/up.sql
- full-service/src/config.rs
- full-service/src/db/gift_code.rs
- full-service/src/db/models.rs
- full-service/src/db/schema.rs
- full-service/src/json_rpc/gift_code.rs
- full-service/src/service/gift_code.rs
- full-service/src/test_utils.rs
As part of my work on upgrading our Rust version I tried upreving `mobilecoin` in this repo in order to bring in some `clippy` fixes but ran into issues that arise from the gift codes changing to support two entropy types (the old root and the new bip39).
* Uprev `mobilecoin` and get `full-service` to support the new bip39-entropied gift codes.
> uprev mobilecoin, add bip39 entropy support to giftcodes

- Cargo.lock
- Cargo.toml
- README.md
- full-service/Cargo.toml
- full-service/src/db/wallet_db.rs
Statically linking sqlite3 means we will have an easier time distributing binaries. Ensuring that all users are running with the same version would make debugging easier if any issues arise. 
* Switch to a fork of `diesel` that allows using a newer version of the `libsqlite3-sys` crate. That version has the required sqlite3 3.35.4 bundled.
> Statically link the correct version of sqlite3

- full-service/src/db/account.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/service/account.rs
- full-service/src/service/address.rs
- full-service/src/service/balance.rs
- full-service/src/service/confirmation_number.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/receipt.rs
- full-service/src/service/transaction.rs
- full-service/src/service/transaction_log.rs
- full-service/src/service/txo.rs
* Move all usage of transactions out of the db layer and into the service
layer.
* Every time we create a connection with get_conn(), start a db transaction.
> Clean up usage of database transactions.

- full-service/src/json_rpc/account.rs
Merchant services needs a way of quickly checking the block index a given account is fully synced to.
* Include `next_block_index` in the `get_account` call.
> include next_block_index in account query

- Dockerfile
Docker runs that use cache will not pick up changes to https://enclave-distribution.[test|prod].mobilecoin.com/production.json since nothing will change in the `RUN` line. 
Solution: use `ADD` to pull down the json.  This should check for server side changes and invalidate cache as necessary.
* Use `ADD` instead of pulling production.json with curl.
> Don't cache production.json 

- DATABASE.md
- README.md
- full-service/Cargo.toml
- full-service/src/bin/main.rs
- full-service/src/db/wallet_db.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/test_utils.rs
* Embed SQLCipher library by static linking.
* Use MC_PASSWORD environment variable to set a password and activate database
encryption.
* Use MC_CHANGE_PASSWORD environment variable to change database password.
> Wallet database encryption via SQLCipher.

- cli/README.md
> Add instructions to the README showing how to install the Python client as a pip package.

- Dockerfile
Soundtrack of this PR: Yakety Sax
Update build image to include libssl-dev package.   Build image also update with latest Ubuntu bionic release.
* Dockerfile: Set RUSTFLAGS `target-cpu=penryn` to match build instructions.
* Dockerfile: Update build image to add libssl-dev package.
> Update base image and add libssl-dev

- full-service/migrations/2021-03-03-035127_api_v2/down.sql
- full-service/migrations/2021-03-03-035127_api_v2/up.sql
- full-service/migrations/2021-03-25-042338_proof_to_confirmation/down.sql
- full-service/migrations/2021-03-25-042338_proof_to_confirmation/up.sql
- full-service/migrations/2021-03-30-021521_slip10_account_key/down.sql
- full-service/migrations/2021-03-30-021521_slip10_account_key/up.sql
- full-service/migrations/2021-03-31-220723_nullable_transaction_log_address/down.sql
- full-service/migrations/2021-03-31-220723_nullable_transaction_log_address/up.sql
- full-service/migrations/2021-04-03-183001_reorder_account_fields/down.sql
- full-service/migrations/2021-04-03-183001_reorder_account_fields/up.sql
- full-service/migrations/2021-04-09-050201_multi_outlay_transaction_logs/down.sql
- full-service/migrations/2021-04-09-050201_multi_outlay_transaction_logs/up.sql
- full-service/migrations/2021-04-20-182449_gift_code_two_entropies/down.sql
- full-service/migrations/2021-04-20-182449_gift_code_two_entropies/up.sql
- full-service/migrations/2021-06-25-225113_transaction_logs_nullable_assigned_subaddress_b58/down.sql
- full-service/migrations/2021-06-25-225113_transaction_logs_nullable_assigned_subaddress_b58/up.sql
- full-service/src/bin/main.rs
- full-service/src/db/wallet_db.rs
SQLite has a bunch of limitations surrounding table altering. When creating migrations that alter tables, we sometime have to make changes that temporarily violate foreign key constraints. For example, quoting [this](https://www.techonthenet.com/sqlite/foreign_keys/foreign_keys.php) page: "You can not use the ALTER TABLE statement to add a foreign key in SQLite. Instead you will need to rename the table, create a new table with the foreign key, and then copy the data into the new table.". However, this renaming/copying eventually involves deleting the original table, which then breaks foreign keys. The workaround is to temporary disable foreign key checks.
The migrations SQL files mistakenly tried to do that, but according to the …
> Fix issues with foreign key migrations

- cli/mobilecoin/cli.py
- cli/mobilecoin/client.py
- cli/test/client_tests.py
Currently, we use the python CLI to build and submit in two separate actions because we need a tx_proposal. For throughput and to allow multithreading without accidentally sending the same uTXO, we would like to pull the tx_proposal from build_and_submit_transaction.
* added to `build_and_submit_transaction_with_proposal` in the python client
[Python client: get tx_proposal from build_and_submit_transactions](https://app.asana.com/0/1200175610893108/1200918570741698) 
* [MOBot: Migrate to new python client for full-service API](https://app.asana.com/0/1200175610893108/1201002142005233)
> Optionally return tx_proposal with build_and_submit_transaction

- .circleci/config.yml
- full-service/Cargo.toml
Ended up removing build-macos stuff because of an issue with serde_json v1.0.72.
> fix mac os build step

- docs/accounts/address/get_address_for_account.md
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
added functionality for getting a subaddress by its index. The address must have already been assigned to prevent users for accidentally getting an address at some random integer and effectively losing the txo's that end up there.
> Get Subaddress by Index

- tools/lint.sh
Soundtrack of this PR: [link to song that really fits the mood of this PR](https://www.youtube.com/watch?v=2Pzq5f6-PYo)
Running the linter in Fullservice fails because it tries to lint the mobilecoin submodule which needs to be run in an enclave. 
Excluding mobilecoin submodule from the linter
> Excluding mobilecoin submodule from linter

- Cargo.lock
- full-service/src/bin/main.rs
- full-service/src/config.rs
- validator/service/Cargo.toml
- validator/service/src/bin/main.rs
- validator/service/src/config.rs
The validator node needs to sync the ledger, similar to other clients.
* Making ledger-related structopt config stuff inside full-service reusable
* Adding the plumbing required to start the LedgerSyncThread inside the validator service.
I tested this locally using this command, and it synced the ledger as expected:
```
SGX_MODE=HW IAS_MODE=PROD CONSENSUS_ENCLAVE_CSS=/home/eran/full-service/consensus-enclave.css cargo run --bin mc-validator-service -- \
--ledger-db /tmp/ledger-db/ \
--peer mc://node1.test.mobilecoin.com/ \
--peer mc://node2.test.mobilecoin.com/ \
--tx-source-url https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node1.test.mobilecoin.com/ \
--tx-source-url https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node2.test.mobilecoin.com/
```
> LedgerDb syncing

- Cargo.lock
- Cargo.toml
- full-service/Cargo.toml
- full-service/src/bin/main.rs
- full-service/src/config.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/lib.rs
- full-service/src/validator_ledger_sync.rs
- validator/connection/Cargo.toml
- validator/connection/src/error.rs
- validator/connection/src/lib.rs
- validator/service/src/bin/main.rs
This PR contains the changes to full-service that allows it to get the ledger, submit transactions and lookup fog reports by using the validator service.
I have tested it locally using testnet and was able to:
* Sync the ledger
* Send a transaction to my desktop wallet account
* Send a transaction to my mobile wallet
* Receive a transaction sent into the full-service account
Next steps:
* In order to ensure full-service, when using this new `--validator` mode, really does not connect anywhere else, this needs to get tested on a firewalled machine that can only make outgoing connections to a single host:port.
* Unit tests for the validator API endpoints might be useful
* Full end to end test with the mirror
Now, for those that are interested in running this, here are the steps I took. …
> Support using the validator service as a backend for full-service

- full-service/Cargo.toml
- full-service/src/bin/main.rs
- full-service/src/check_host.rs
- full-service/src/config.rs
- full-service/src/lib.rs
- validator/service/src/bin/main.rs
Motivation
When using the --validator option and LVN, the LVN should perform the IP checking and not full-service.
In this PR
Add IP checking to LVN
Skip IP checking in full-service when running with --validator
> First draft removing ip check feature and adding ipcheck for validator

- full-service/src/bin/main.rs
- validator/connection/src/lib.rs
I ran into this log message today:
```
"details": "Error building transaction: Error generating FogPubkeyResolver Error fetching fog reports for [Uri { url: Url { scheme: \"fog\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"fog.prod.mobilecoinww.com\")), port: None, path: \"/\", query: None, fragment: None }, host: \"fog.prod.mobilecoinww.com\", port: 443, use_tls: true, username: \"\", password: \"\", _scheme: PhantomData }]: GRPC: RpcFailure: 14-UNAVAILABLE failed to connect to all addresses"
```
Initially it appeared to me as if `fog.prod.mobilecoinww.com` was not responding, but in reality it was the validator node that was not responding. This confusion will make future debugging more difficult, so I am proposing to make some logging more verbose.
* …
> Make logging of validator-related failures more explicit

- Dockerfile
Soundtrack of this PR: [Jaco Pastorius - Portrait of Tracy](https://www.youtube.com/watch?v=nsZ_1mPOuyk)
The full-service docker container needed to be updated with a new builder image reference, as well as a base image reference, so that all images used Ubuntu Focal Fossa (20.04) and had the correct dev packages installed for the build.
* Uses an updated builder image sha reference (that contains `pkg-config`)
* Uses an updated base image (Ubuntu 20.04)
* None
> Update builder and base image references

- full-service/migrations/2022-02-08-225206_simplify_gift_codes/down.sql
- full-service/migrations/2022-02-08-225206_simplify_gift_codes/up.sql
- full-service/src/bin/main.rs
- full-service/src/db/gift_code.rs
- full-service/src/db/models.rs
- full-service/src/db/schema.rs
- full-service/src/json_rpc/gift_code.rs
- full-service/src/service/gift_code.rs
- full-service/src/util/b58/mod.rs
> Remove unnecessary foreign keys from gift_codes table.

- full-service/src/bin/main.rs
> Remove foreign key check before running migrations. This allows databases with existing foreign key errors to be fixed by the migrations.

- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/test_utils.rs
1) Start full-service with an empty ledger and an empty wallet db
2) Import an account from entropy, giving it a first_block of 0
3) The ledger sync process will enter one block at a time into the
ledger DB. The account sync process will then attempt to decode
transactions from these blocks in very small chunks, of size 5-10
(instead of ten thousand), with no sleeping in between. Furthermore, the
first account will do all of the syncing, not letting any other accounts
sync at the same time.
In order to fix this, the condition for reporting whether the sync
thread can pause was updated to more elegantly handle this condition, by
counting the number of blocks synced, and comparing it to the ideal
chunk size.
> Fix a bug causing sync to create many tiny chunks.

- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/service/balance.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/receipt.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction.rs
- full-service/src/service/txo.rs
- full-service/src/test_utils.rs
Soundtrack of this PR: [No Ghosty](https://soundcloud.com/swrlyy/no-ghosty)
We don't actually need to provide a target block index. Instead, let the account sync up to the most recent block.
- Remove target block index arg from `manually_sync_account` fn.
- Remove that arg from all calls to that fn.
[Ticket](https://app.asana.com/0/1200175610892874/1201832364350094/f)
> Remove block index arg from manual account sync test util

- .github/workflows/ci.yml
Soundtrack of this PR: [Fantasy Ambient](https://www.youtube.com/watch?v=AohPsuy65hQ)
Currently there is no automated build of Docker images for Full-Service so updates lag behind the code.  This adds a github action to build and publish docker images when a tag is pushed
* Adds a github action workflow to build docker images for testnet and mainnet.
* Currently only builds images when a tag is pushed.
* Added the `-testnet` and `-mainnet` suffixes to the images for better clarification.
* Commented out a `tests` job placeholder for Mikey who is currently working on some stress tests.
* Defined the `develop` and `feature/**` filters so when the tests are put in they should run for any push to those branches.  This is also just a placeholder and should be adjusted when the test action is …
> Initial action to build containers for tag pushes

- full-service/src/db/account.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/txo.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/balance.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/receipt.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction.rs
- full-service/src/service/txo.rs
- full-service/src/test_utils.rs
Since we were defaulting to empty string when creating the account key, it makes it easier to deal with this earlier in the chain and simply turn null values for fog creds into empty strings at the RPC layer
> FOG Creds default to empty string if not provided from API

- .gitignore
- README.md
- docs/tutorials/environment-setup.md
- full-service/src/bin/main.rs
- full-service/src/db/wallet_db.rs
- full-service/src/json_rpc/api_test_utils.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/wallet.rs
Increase security on the full-service wallet's jsonrpc loop.  
* Full-service now examines an MC_API_KEY environment variable. If the environment variable is left blank, no checks will be performed. However, if the environment variable is set, an equality check will be performed, looking for an X-API-KEY header in the incoming http request. If these are not equal, an error will be returned. If this header does equal the environment variable, the jsonrpc command will be performed.
* The API key sourced from an env var and then added to the Rocket client's state. This allows us to source the API key from places other than the env var without changing the code for the request guard, which is particularly useful in testing. Testing with env vars in Rust is a bit fraught. Env vars are shared …
> Api key guard

- .circleci/config.yml
1.25 was published with https://github.com/mobilecoinfoundation/mobilecoin/pull/1307
> Update builder-install image version used in CI

- docs/transactions/txo/README.md
- docs/transactions/txo/get_txos_for_view_only_account.md
- full-service/migrations/2022-02-28-190052_view-only-accounts-and-txos/down.sql
- full-service/migrations/2022-02-28-190052_view-only-accounts-and-txos/up.sql
- full-service/src/db/models.rs
- full-service/src/db/schema.rs
- full-service/src/db/view_only_txo.rs
- full-service/src/json_rpc/view_only_txo.rs
I preparation for using imported transactions to update the balance of view-only accounts, add a public key field to view-only txos. When importing a transaction proposal, we will create a temporary log that records all of the public keys for inputs and outputs in the proposal and any existing view-only-txos whose public key matches any of the input TXOs. On ledger updates, we will look for txos with keys that match the logged outputs. If any keys match, we will update the related view-only txo as spent and delete the log.
Edit migration to add new column to table.
Update create method to populate field.
[Ticket](https://app.asana.com/0/1200175610892874/1202001794683748/f)
* Implement rest of flow described above.
* Add ability to export txos for an account and import view-only txos for …
> Add public key field to view only txo

- full-service/src/db/view_only_txo.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/txo.rs
- full-service/src/service/view_only_txo.rs
for users with hot&cold wallets, give them the ability to build a transaction proposal on their cold full-access wallet, then set any spent txos to spent on their hot view-only wallet.
Add export_spent_txo_ids endpoint
Add set_view_only_txos_spent endpoing
[Ticket](https://app.asana.com/0/1200175610892874/1202001794683752/f)
see description of [273](https://github.com/mobilecoinofficial/full-service/pull/273)
> Export spent txos and mark spent

- full-service/src/db/account.rs
- full-service/src/db/view_only_account.rs
- full-service/src/db/view_only_transaction_log.rs
- full-service/src/db/view_only_txo.rs
- full-service/src/json_rpc/api_test_utils.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/sync.rs
- full-service/src/service/view_only_account.rs
- full-service/src/test_utils.rs
Bugs fixed:
* When creating an account, it sets the next block index equal to the
current block, forcing the current block to re-sync unnecessarily.
* When creating an account offline, it continues to endlessly sync the
account past the zero blocks that are known in the ledger.
* When creating an account offline with no ledger, the first block is
set to negative one, which overflows to <u64>::MAX - 1
> Bugfixes for offline account creation.

- cli/mobilecoin/cli.py
- cli/mobilecoin/client.py
Add functionality to export view keys for a spendable account.
Allow importing view keys.
Display view key balance in `mobcli list`.
> Implement view-key management through CLI.

- .mobconf
- rust-toolchain
This makes `full-service` follow whatever versions are in the `mobilecoin` submodule, i.e. fewer references to update when upgrading the `rust-toolchain` or `builder-install` image. Updates can then be propagated when updating the submodule.
> Make .mobconf and rust-toolchain reference mobilecoin submodule

- docs/FAQ.md
- docs/README.md
- docs/SUMMARY.md
https://github.com/mobilecoinofficial/full-service/issues/301
> Add FAQ to docs and document precision

- full-service/src/db/transaction_log.rs
- full-service/src/service/transaction_builder.rs
To better support RTH, a change TXO should always be included in a transaction, even when the total change would be 0 MOB.
* Add change output, regardless of change value
https://github.com/mobilecoinofficial/full-service/issues/310
> Add change output for zero change

- docs/SUMMARY.md
- docs/accounts/account-secrets/export_view_only_account_package.md
- full-service/src/json_rpc/json_rpc_response.rs
- full-service/src/json_rpc/view_only_account.rs
- full-service/src/json_rpc/wallet.rs
The API endpoint was exporting the VO account import package as an encapsulated "package" object instead of returning the internal structure flattened. This change also returns the full json_rpc_request body as a response, identical to how the transaction signer functions.
> Updating export VO package for normal accounts

- full-service/src/service/transaction.rs
There is a limit (16) on the number of inputs and outputs for a transaction. This limits is enforced by the mobilecoin lib but not by full service. Right now you could build a transaction in full service using an invalid number of ins/outs and submit it, only to have it fail in consensus. This PR enforces those limits in full service, so that users get better feedback about their transactions before submitting them to consensus.
> Enforce transaction input and outputs limits

- .github/release.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
> Update actions to include ARM64 build (M1 Mac)

- full-service/src/service/sync.rs
We only want to have transaction logs for MOB tokens until we add full support in the future
> Only create tx_log when Token is MOB

- Cargo.lock
- full-service/src/bin/main.rs
- full-service/src/config.rs
- validator/service/src/bin/main.rs
This should be included in a full-service wallet release by July 14th to comply with the Intel SGX security advisory deadline.
> Add Intel SA 615 to MrSigner verifier.

- docs/transactions/txo/get_txos_for_account.md
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/migration_testing/seed_txos.rs
- full-service/src/db/txo.rs
- full-service/src/db/wallet_db_error.rs
- full-service/src/json_rpc/e2e.rs
- full-service/src/json_rpc/json_rpc_request.rs
- full-service/src/json_rpc/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/balance.rs
- full-service/src/service/receipt.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/txo.rs
- full-service/src/test_utils.rs
Allow users to query for txos with a specific status.
* Add optional status field to get txos query
* Inside of get txos db model fn, route query to appropriate fn based on status argument.
* Update txo db model queries to use optional pagination args
> Add status option for get txos endpoint

- full-service/src/db/txo.rs
- full-service/src/json_rpc/e2e_tests/account/create_import/view_account_flow.rs
- Update query to include check for key image
- Add tests to validate query
> List unspent txos should only return txos with both a key image and subaddress

- full-service/src/db/transaction_log.rs
- full-service/src/db/view_only_txo.rs
Update queries for transaction logs to remove logs + txos for non-mob-tokens from results.
Update the one VO txo query that didn't already filter out non-mob-tokens.
Went through all other models and services to make sure that queries that return/relate to txos filter out non-mob-tokens.
Did not change sync logic. figured that queries involved in sync should still apply to non-mob-tokens
> Release 1.9.x Remove non-mob-tokens from queries

- Cargo.lock
- full-service/Cargo.toml
- full-service/src/bin/main.rs
- full-service/src/config.rs
- full-service/src/db/account.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/txo.rs
- full-service/src/service/account.rs
- full-service/src/service/address.rs
- full-service/src/test_utils.rs
- validator/service/src/bin/main.rs
fixes accounts that are migrating from 1.8 -> 1.9+ that are using the legacy change address by auto assigning the new change subaddress, which will collect any orphaned txos sent to that address by transactions made with 1.9+
> assigns new change subaddress on startup if missing

- full-service/migrations/2022-06-13-204000_api_v3/up.sql
- full-service/src/db/account.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/models.rs
- full-service/src/db/schema.rs
- full-service/src/json_rpc/v1/api/wallet.rs
- full-service/src/json_rpc/v1/models/address.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/e2e_tests/account/account_address.rs
- full-service/src/json_rpc/v2/e2e_tests/account/account_balance.rs
- full-service/src/json_rpc/v2/e2e_tests/account/account_other.rs
- full-service/src/json_rpc/v2/e2e_tests/account/create_import/import_account.rs
- full-service/src/json_rpc/v2/e2e_tests/transaction/transaction_txo.rs
- full-service/src/json_rpc/v2/models/address.rs
- full-service/src/service/balance.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/payment_request.rs
- full-service/src/service/receipt.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction.rs
- full-service/src/service/transaction_log.rs
- full-service/src/service/txo.rs
We were storing duplicate data that didn't need to be stored, and had unnecessary fields.
* Removed address book entry (unused)
* Removed encoded public address (can be obtained from the public address b58)
* Renamed other fields to be more explicit
* Updated model to reflect these changes where necessary
* Remove assigned addresses for reserved subaddresses defined in the mc library (currently default subaddress, change subaddress, and gift code subaddress).
> Update AssignedAddress db schema and JSON model

- full-service/src/db/txo.rs
building transactions with multiple txos was failing because of a bug in the txo selection join query, which was resolved by calling "distinct"
> bug fixed by selecting distinct

- full-service/Cargo.toml
- validator/api/Cargo.toml
- validator/connection/Cargo.toml
- validator/service/Cargo.toml
On mac, using openSSL is not feasible because it will require users to install it manually.
> Upgrade GRPCIO to fix openssl problem

- full-service/src/db/txo.rs
- full-service/src/service/balance.rs
- full-service/src/service/transaction.rs
- full-service/src/service/transaction_builder.rs
Now returns an error if the default fee for a selected token cannot be found and isn't provided.
Also updated the max spendable logic to take in a default_token_fee that is specified by the calling function, which will eventually support mixed token transactions
> Error report for invalid token network fee and getting max spendable for token

- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/v1/api/wallet.rs
- full-service/src/json_rpc/v2/api/test_utils.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/receipt.rs
- full-service/src/service/transaction.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/transaction_log.rs
- full-service/src/service/txo.rs
- full-service/src/test_utils.rs
In an effort to simplify and centralize the logic around building and signing transactions, this moves all duplicate/similar logic into a single source of truth
> Refactor Transaction Building

- docs/SUMMARY.md
- docs/v2/api-endpoints/get_txo_membership_proofs.md
- docs/v2/api-endpoints/sample_mixins.md
- full-service/src/db/models.rs
- full-service/src/db/txo.rs
- full-service/src/db/wallet_db_error.rs
- full-service/src/json_rpc/v2/api/request.rs
- full-service/src/json_rpc/v2/api/response.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/service/ledger.rs
- full-service/src/service/txo.rs
Porting functionality from mobilecoind to expose txo membership proofs from TxOut objects and sampling the ledger for tx outs to use as mixins.
> Sample Mixins & Get Txo Membership Proofs

- Cargo.lock
- Cargo.toml
I'm having issues building under some CI configuration (surfaced by https://github.com/mobilecoinfoundation/mobilecoin/pull/2543), and I believe this should resolve it.
* Remove an unnecessary override of `packed_simd_2` since a newer version has since been released.
> remove no longer needed override of packed_simd

- docs/SUMMARY.md
- docs/v2/api-endpoints/get_txo_block_index.md
- docs/v2/api-endpoints/validate_tx_out.md
- full-service/src/json_rpc/v2/api/request.rs
- full-service/src/json_rpc/v2/api/response.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/e2e_tests/other.rs
- full-service/src/service/ledger.rs
Adds the ability to check the block index of a txo's public key, if it exists on the ledger
Todo:
> Get Block Index by TXO public key

- full-service/src/db/account.rs
This makes it so that when importing and account that exists, it will now return the account_id with the error.
> Checking if account already exists

- README.md
- docs/SUMMARY.md
- docs/usage/no-wallet-db/no-wallet-db.md
- full-service/src/bin/main.rs
- full-service/src/config.rs
- full-service/src/db/wallet_db_error.rs
- full-service/src/error.rs
- full-service/src/json_rpc/v1/api/test_utils.rs
- full-service/src/json_rpc/v2/api/test_utils.rs
- full-service/src/json_rpc/v2/e2e_tests/other.rs
- full-service/src/service/account.rs
- full-service/src/service/address.rs
- full-service/src/service/balance.rs
- full-service/src/service/confirmation_number.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/ledger.rs
- full-service/src/service/payment_request.rs
- full-service/src/service/receipt.rs
- full-service/src/service/sync.rs
- full-service/src/service/transaction.rs
- full-service/src/service/transaction_log.rs
- full-service/src/service/txo.rs
- full-service/src/service/wallet_service.rs
- full-service/src/test_utils.rs
- tools/run-testnet-no-wallet-db.sh
This enables full service to be started without a wallet_db config, which puts it into a mode that disables any endpoints that require interacting with the wallet_db.
Currently, if an existing endpoint that is disabled is called, it will return an error with an appropriate description.
```
{
"method": "get_accounts",
"error": {
"code": -32603,
"message": "InternalError",
"data": {
"server_error": "Database(WalletFunctionsDisabled)",
"details": "Error interacting& with the database: Wallet functions are currently disabled"
}
},
"jsonrpc": "2.0",
"id": 1
}
```
but still allows for non wallet-db interacting API methods to be called as normal
```
{
"method": "get_network_status",
"result": {
"network_status": {
"network_block_height": "1031460",
"local_block_height": "1031460",
"fees": {
"0": …
```
> Feature/No Wallet Db Mode (Partial-Service)

- docs/v2/api-endpoints/get_network_status.md
On the v2 api docs, the example response for get_network_status is out of date.
Updated the v2 api docs for get_network_status  example response to show "fees": {}  in the response instead of the v1 api's "fee_pmob" response element.
> updated fee_pmob to fees: {} in v2 api docs for get_network_status

- full-service/src/bin/main.rs
- full-service/src/service/balance.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/ledger.rs
- full-service/src/service/transaction.rs
- full-service/src/validator_ledger_sync.rs
- validator/connection/src/lib.rs
- validator/service/src/blockchain_api.rs
- validator/service/src/validator_api.rs
We discovered a few issues as a result of the recent switch to block version 2.
* Fixing `mc-validator-service` to properly forward the complete fee map and block version
* Change fee map handling - prior to this PR we chose the max fee for each token, but that allows a malicious node to do a grief attack and trick clients into higher than necessary fee. This PR changes the strategy around this, and instead enforces that all nodes are in agreement about the fee map. If they aren't, that indicates a network fork and should be carefully handled by the operator.
* Make `mc-validator-service` validate chain-id headers if the chain-id argument is passed to it.
> Fix issues surfaced by block version 2

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
- docs/tutorials/environment-setup.md
- full-service/Cargo.toml
to standardize the naming of our binaries, changing full-service to mc-full-service
also adding some ci changes to allow for dev builds
> update build and release and full-service binary name

- .github/workflows/build.yml
- .github/workflows/release.yml
Consolidating duplicated code
Changing the copied binaries for full-service to mc-full-service
Adjusting the release script to reflect these changes
> Update github actions to consolidate duplicated code for building

- full-service/src/config.rs
after discussion with @holtzman and reviewing discussion in Slack, we decided to make this field optional to not break existing scripts. May revisit in the future.
> making chain-id optional and default to empty string

- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/v1/api/wallet.rs
- full-service/src/json_rpc/v2/api/request.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/receipt.rs
- full-service/src/service/transaction.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/service/transaction_log.rs
- full-service/src/service/txo.rs
- full-service/src/test_utils.rs
This adds the ability for a user to specify which subaddress to generate their Sender Memo Credential from for RTH memos (full reasoning in the linked issue).
The main change is adding an optional parameter to the build_transaction and build_and_submit_transaction endpoints.
> Specify Subaddress for Sender Memo Credential

- .github/workflows/ci.yml
- full-service/Cargo.toml
- mirror/Cargo.toml
- transaction-signer/Cargo.toml
- validator/connection/Cargo.toml
- validator/service/Cargo.toml
Rust has opinions about formatting of `.rs` and `Cargo.toml` files and CI should enforce that.
> Make CI enforce Rust formatting/conventions

- full-service/src/service/ledger.rs
- full-service/src/service/transaction.rs
- validator/service/src/blockchain_api.rs
- validator/service/src/validator_api.rs
Currently if the attestation connection has been invalidated by consensus it will simply fail the transaction. This will alleviate that error by adding retry logic (up to 5 times of increasing intervals of time based on the Fibonacci sequence starting at 10ms)
> adding retry logic for attestation errors

- .github/workflows/docker-hub.yml
Some users rely on the docker hub images and would like to test with pre releases
> dockerhub image includes pre-release

- full-service/src/json_rpc/v2/models/transaction_log.rs
Keeping txo_id also to prevent a second breaking change for anyone who has already implemented to breaking change fix
> Adding back txo_id_hex to undo breaking change

- docs/v2/api-endpoints/get_blocks.md
- docs/v2/api-endpoints/get_recent_blocks.md
- full-service/src/json_rpc/v2/api/request.rs
- full-service/src/json_rpc/v2/api/response.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/e2e_tests/other.rs
- full-service/src/json_rpc/v2/models/network_status.rs
- full-service/src/service/balance.rs
- full-service/src/service/ledger.rs
These endpoints are needed for implementing a block explorer. In theory the `get_recent_blocks` endpoint can be implemented by using a combination of `get_blocks` and `get_network_status`, but it is simple enough that I figured it's nice to just have it.
Two new endpoints: `get_blocks` and `get_recent_blocks` in the V2 API.
Unit tests were added.
> Add endpoints for getting recent blocks and range of blocks

- full-service/migrations/2023-01-20-231044_add_index_to_subaddress_spend_key/down.sql
- full-service/migrations/2023-01-20-231044_add_index_to_subaddress_spend_key/up.sql
- full-service/src/db/txo.rs
- full-service/src/service/sync.rs
- full-service/src/test_utils.rs
This update was necessary to increase account sync speed for accounts with large amounts of subaddresses, as well as not causing the API to lock when syncing any account. The main fix is that we are no longer using a transaction nor pre-generating all of the subaddress keys for each iteration, since the subaddress keys already exist in the database and we can simply perform a SQL query to match against them.
> removing account syncing requiring regenerating subaddress keys

- docs/v2/api-endpoints/search_ledger.md
- full-service/src/json_rpc/v2/api/request.rs
- full-service/src/json_rpc/v2/api/response.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/e2e_tests/other.rs
- full-service/src/json_rpc/v2/models/block.rs
- full-service/src/json_rpc/v2/models/ledger.rs
- full-service/src/json_rpc/v2/models/mod.rs
- full-service/src/service/ledger.rs
- full-service/src/service/models/ledger.rs
- full-service/src/service/models/mod.rs
We'd like to have the option to search the ledger by tx out public keys, key images, and later on TxoIDs (and maybe other things).
* Initial implementation of a basic `search_ledger` endpoint.
Unit test was added to cover the basic functionality.
* Expand search to cover more queries, such as TxoIDs.
> A basic search endpoint

- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/service/ledger.rs
- full-service/src/service/sync.rs
- full-service/src/test_utils.rs
Account syncing was still locking the database when importing an account from block 0
* Changed account sync to sync 1000 blocks max per iteration across all accounts before taking a slight pause to allow other code to execute. This is required because account syncing write locks the wallet_db, and previously it would loop and sync until it was up to date, which was unintentional.
> Account sync pause every 1000 blocks

- Cargo.lock
- full-service/Cargo.toml
- full-service/src/bin/main.rs
- full-service/src/config.rs
- full-service/src/json_rpc/v1/api/test_utils.rs
- full-service/src/json_rpc/v2/api/response.rs
- full-service/src/json_rpc/v2/api/test_utils.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/e2e_tests/other.rs
- full-service/src/json_rpc/v2/models/block.rs
- full-service/src/json_rpc/v2/models/ledger.rs
- full-service/src/json_rpc/v2/models/mod.rs
- full-service/src/json_rpc/v2/models/watcher.rs
- full-service/src/service/ledger.rs
- full-service/src/service/mod.rs
- full-service/src/service/models/ledger.rs
- full-service/src/service/models/mod.rs
- full-service/src/service/models/watcher.rs
- full-service/src/service/wallet_service.rs
- full-service/src/service/watcher.rs
- full-service/src/test_utils.rs
This information is needed by the new block explorer, and might also be useful for other users who want access to timestamps and block signatures.
Adding an optional syncing of a `WatcherDB` and exposing the data provided by it, when available, via the V2 API
I tested this manually. Example response looks like this:
```
...
"watcher_info": {
"timestamp": "1673991888",
"timestamp_result_code": "TimestampFound",
"signatures": [
{
"src_url": "https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node1.test.mobilecoin.com/",
"archive_filename": "00/00/00/00/00/14/e6/000000000014e648.pb",
"block_signature": {
"signature": "31e7de448588e62dca608bde40b0e4d63f091385c420ef5734a27307c523b9a13aa9fabe78dd5f3efe9aed790351ed7a063e1e601c944ff626cb8f1e1bfca20f",
"signer": …
```
> Add watcher information to v2 responses that include block information

- full-service/src/bin/main.rs
This prevents the sync thread from dropping out of scope when the function it's created in returns, similar to how we are handling the ledger sync thread.
> Add watcher sync thread to rocket.manage

- full-service/src/service/balance.rs
This helps speed up the get account status endpoint by making sure to only query the network a single time for the latest block info, instead of separately for each piece of information it's looking for.
> Only query for network block info a single time when getting account status

- README.md
- full-service/src/config.rs
> Fixing various typos, etc

- full-service/migrations/2023-02-15-225147_add_index_to_subaddress_index/down.sql
- full-service/migrations/2023-02-15-225147_add_index_to_subaddress_index/up.sql
an alternate solution to the assign next subaddress slowdown as the number of subaddresses increases for an account. For more info, see #712
> adding index to assigned subaddress on subaddress index

- .github/workflows/ci.yml
- .github/workflows/dev-cd.yaml
Since the [gitbook docs](https://mobilecoin.gitbook.io/full-service-api/) are attached to the `main` branch but we had been using `develop` as our primary branch (and not really using `main`), the easiest thing to do was just to rename `develop` to `main`
> updating branches from develop->main

- mirror/src/private/main.rs
This is to enable all v1 endpoints that were missing compared to the full-service-mirror repo
> adding the collection of v1 endpoints to mirror allowed endpoints

- .github/workflows/build.yml
- .github/workflows/release.yml
This is to allow CI to run smoothly for the 2.3 series, which is not working on mac at the moment. This has been resolved in 2.4, so this PR should not be merged back in.
> removing mac builds - only for v2.3 series

- Cargo.lock
Keeping release branches of full service tied to finalized release branches of the mobilecoin repo is important to ensure stability of features.
* Reverted bump of mc to latest master
* Set mc to brian/4.0.2/watcher-db-cherry-pick, which is necessary to keep the watcher functionality working. This was a very small PR that only added serde implementations
* Bump mc to 4.1.0 when released to get off of cherry picked version of 4.0.2
> Revert mc to 4.0.2

- docs/v1/api-endpoints/verify_address.md
- docs/v2/api-endpoints/verify_address.md
Address does not need to be part of wallet to be validated
The docs are inaccurate in that the address to be verified doesn't actually need to be under an account within FS - it's just a B58 verifier.
> removing inaccurate requirement

- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/e2e_tests/other.rs
- full-service/src/util/b58/tests.rs
- python/mobilecoin/cli.py
- python/mobilecoin/client.py
- Add token-id to payment request results from check_b58_type.
- Implement payment requests in Python API and CLI.
> Implement payment requests for all token types.

- mirror/test/start.sh
- mirror/test/stop.sh
- tools/.shared-functions.sh
- tools/run-fs.sh
Run manual testing of full-service + mirror + validator-service.
* Add `--validator` option to `run-fs.sh` script to configure full-service and start the validator-service .
```
tools/build-fs test
cd mirror/test
./start.sh --network test
./test.sh --mnemonic '<24 words>'
./stop.sh
```
* When using the validator-service, full-service only knows about the blocks validator-service has loaded. So monitoring `get_wallet_status` to wait for full-service to be ready doesn't really work. 
* The shell scripts I'm using to start and monitor the services are getting clunky.  We should consider something like `supervisord` to manage the processes for local testing.
* Watching `get_account_status`, `next_block_index` vs `local_block_height` on a new account import doesn't seem to be an accurate …
> 2.3 - fix: Add validator-service to mirror testing setup

- tools/build-fs.sh
- tools/run-fs.sh
Small change in tools/run-fs.sh helper script to fix the chain-id logic when running on `main` or the legacy `prod` networks.
```
tools/build-fs.sh main
tools/run-fs.sh prod
OR
tools/run-fs.sh main
```
> v2.3 - fix: set chain-id to main for main|prod network

- mirror/test/start.sh
- mirror/test/test.sh
- mirror/test/v1/test_lib/package.json
- mirror/test/v1/test_lib/send-request-encrypted.js
- mirror/test/v1/test_suite/package.json
- mirror/test/v1/test_suite/test_script.js
- tools/.shared-functions.sh
- tools/build-fs.sh
- tools/run-fs.sh
Primary: Add v1 API mirror tests.
Secondary: 
- Improve helper scripts to launch v1 and v2 copies of mirror. Listening of ports 9091 and 9092 respectively.
- Separate target directories for main vs test cargo builds. 
- Detect `mob prompt` container and allow full-service and public mirror endpoint "publish" and use storage for ledger/wallet db's that will be persistent (.mob directory)
```
tools/build-fs.sh main
cd mirror/test
./start.sh --network main
./test.sh --mnemonic "<24 words>"
```
> Add v1 api mirror tests

- BRANCHING.md
This is heavily inspired (and copied mostly) by the branching document from the mobilecoin repo. Thank you @jcape!
> #### TLDR
> - Changes are typically created on topic branches, reviewed as PRs, and squash-merged into `main`.
> - Major releases are started by creating a release branch e.g. `release/v4.0` off of `main`.
> - Minor releases are started by creating a release branch e.g. `release/v4.1` off of the predecessor `release/v4.0`.
> - Changes which are made in release branches are propagated forward to main, by _merging_ the release branch into main.
> - Developers make changes using topic branches and PRs, and are free to squash-merge their topic branches as they historically have.
> - When a developer wants to make a change, they should ask themselves, should this go in the …
> adding BRANCHING.md

- Cargo.toml
FS builds on linux were > 600MB, and now they are < 30 :)
> adding strip symbols

- docs/v1/api-endpoints/get_txos_for_account.md
- docs/v2/api-endpoints/get_txos.md
- full-service/src/service/account.rs
- full-service/src/service/address.rs
- full-service/src/service/balance.rs
- full-service/src/service/confirmation_number.rs
- full-service/src/service/gift_code.rs
- full-service/src/service/ledger.rs
- full-service/src/service/payment_request.rs
- full-service/src/service/receipt.rs
- full-service/src/service/transaction.rs
- full-service/src/service/transaction_log.rs
- full-service/src/service/txo.rs
- full-service/src/service/watcher.rs
Use rust doc to enhance documentations of full service
Add inline arguments for all methods of `mc_full_service::service` module
Documentations change only. Need manual test or view
> Implement rustdoc for all services modules in full service

- .github/workflows/dev-cd.yaml
to enforce status in CI, needs to be named something else because "test" already exists (for unit tests)
> rename test to integration-test

- full-service/src/bin/main.rs
- full-service/src/config.rs
- full-service/src/json_rpc/v1/api/test_utils.rs
- full-service/src/json_rpc/v2/api/test_utils.rs
- full-service/src/json_rpc/v2/models/network_status.rs
- full-service/src/service/balance.rs
- full-service/src/service/wallet_service.rs
- full-service/src/test_utils.rs
- python/tests/test_client.py
We want to augment `get_network_status` so that users can provide more information about their setup when debugging or reporting issues.
We augment `get_network_status` to give more information about the launching configuration of the full-service instance.
> Augment get_network_status with more information

- .github/workflows/ci.yml
Fixing an out of date rust toolchain causing compilation to fail when running tests because it requires a rust toolchain higher than the one set.
This should have been updated in the past anyways, as they should all be running on the same toolchain.
> updating rust toolchain for ci test

- .github/actions/mobilecoin-cache-cargo-package/action.yaml
- .github/actions/mobilecoin-cache-rust-binaries/action.yaml
- .github/workflows/dev-cd.yaml
- .internal-ci/docker/Dockerfile.full-service
- .internal-ci/docker/entrypoints/full-service.sh
- .internal-ci/docker/support/full-service/initialize-wallets.sh
- .internal-ci/helm/full-service-mirror/.helmignore
- .internal-ci/helm/full-service-mirror/Chart.yaml
- .internal-ci/helm/full-service-mirror/templates/NOTES.txt
- .internal-ci/helm/full-service-mirror/templates/_helpers.tpl
- .internal-ci/helm/full-service-mirror/templates/full-service-configMap.yaml
- .internal-ci/helm/full-service-mirror/templates/full-service-secret.yaml
- .internal-ci/helm/full-service-mirror/templates/full-service-service.yaml
- .internal-ci/helm/full-service-mirror/templates/full-service-statefulSet.yaml
- .internal-ci/helm/full-service-mirror/templates/private-deployment.yaml
- .internal-ci/helm/full-service-mirror/templates/private-secret.yaml
- .internal-ci/helm/full-service-mirror/templates/public-deployment.yaml
- .internal-ci/helm/full-service-mirror/templates/public-service.yaml
- .internal-ci/helm/full-service-mirror/templates/validator-configMap.yaml
- .internal-ci/helm/full-service-mirror/templates/validator-service.yaml
- .internal-ci/helm/full-service-mirror/templates/validator-statefulSet.yaml
- .internal-ci/helm/full-service-mirror/values.yaml
- .internal-ci/helm/full-service/templates/full-service-service.yaml
- full-service/src/config.rs
- tools/.shared-functions.sh
- tools/build-fs.sh
- tools/run-fs.sh
Integration test standalone full-service and full-service with mirror and validator on testnet.
Full-service
* minor fix for full-service option - MC_WATCHER_DB to use clap
Charts/Docker
* make dockerfile "batteries included" - sets MC_PEER, MC_TX_SOURCE_URL for test/main builds.
* update runtime container base image
* Improve fs container entrypoint script, MC_READ_ONLY option, MC_VALIDATOR detection, and restore from MC_LEDGER_DB_URL
* Optional: Import wallets on startup - still needs a bit of work.
* Add full-service-mirror helm chart for deploying setup in k8s clusters
* standardize configuration for full-service and full-service-mirror charts.
CI/CD
* Add cache key differentiation for test/main builds.
* Use mobilecoinofficial/gh-actions for "standard" cache and checkout actions.
* …
> Integration testing fs/fsm+validator - TestNet

- Cargo.lock
- Cargo.toml
This fixes a bug on macOS when using command line tools for Xcode 14.3+
> update mbedtls version

- full-service/src/json_rpc/v1/api/request.rs
- full-service/src/json_rpc/v1/api/wallet.rs
- full-service/src/json_rpc/v1/e2e_tests/account/create_import/import_account.rs
- full-service/src/json_rpc/v2/api/request.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/e2e_tests/account/create_import/import_account.rs
- full-service/src/service/account.rs
This is a legacy field from a long time ago when the import and import_from_legacy_root_entropy methods were combined. Since they have been separated, it no longer is necessary to specify the KDV
> remove key derivation version param

- validator/README.md
Updated Binary name to reflect build changes
cargo build is generating a new filename, this updates the readme to be accurate.
> removing mc- prefix

- python/mobilecoin/token.py
- python/tests/test_client.py
Alpha and TestNet define token 8192, aka Fauxble Dollar aka FauxUSD.  The `mob` cli crashes when any FauxUSD has been used within an account that is imported to `mob`'s full-service. 
This PR adds token 8192 with 6 decimals and a display precision of 2 to the TOKENS table in tokens.py, allowing `mob` to be be more useful when used with TestNet and Alpha.
> Add token 8192, FauxUSD to mob cli's known tokens list

- full-service/src/json_rpc/v1/e2e_tests/transaction/build_submit/build_and_submit.rs
- full-service/src/json_rpc/v1/e2e_tests/transaction/transaction_other.rs
- full-service/src/json_rpc/v1/models/transaction_log.rs
- full-service/src/json_rpc/v2/models/transaction_log.rs
This is to support more easily finding the public key for input and output txos in a transaction
> add public_key to v1 transaction_log txo_abbrevs

- .github/workflows/refresh-ledger.yaml
A previous change in the packaging directory structure of the releases did not include updates to the ledger-refresh process that keeps ledger data synced for testing.  This change fixes that.
* Strip leading directory component in the un-tar of the release package, to match previous behavior.
* Only the GitHub action is updated, so no code changes were made.
* nothing forseen
> Update ledger refresh job to strip leading directory tar components

- .gitmodules
- Cargo.lock
- Cargo.toml
- tools/lint.sh
Addition of the ledger-mob submodule to support other PRs in ledger hardware wallet support
> hardware-wallet/base

- .github/workflows/ci.yml
- Cargo.lock
- full-service/Cargo.toml
- full-service/migrations/2023-03-08-183917_account-managed-by-hardware-wallet-flag/down.sql
- full-service/migrations/2023-03-08-183917_account-managed-by-hardware-wallet-flag/up.sql
- full-service/src/db/account.rs
- full-service/src/db/assigned_subaddress.rs
- full-service/src/db/models.rs
- full-service/src/db/schema.rs
- full-service/src/json_rpc/v2/api/request.rs
- full-service/src/json_rpc/v2/api/response.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/models/account.rs
- full-service/src/service/account.rs
- full-service/src/service/address.rs
- full-service/src/service/hardware_wallet.rs
This adds the idea of "managed by hardware wallet" to accounts, which will prompt them to try to interface with a hardware wallet when performing transactions that required the private spend key.
> hardware-wallet/import-from-ledger

- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/service/hardware_wallet.rs
- full-service/src/service/models/tx_proposal.rs
This adds a check to make sure the account is the expected one prior to executing the operations.
> add hw wallet account check prior to executing operations

- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/models/tx_proposal.rs
- full-service/src/service/models/tx_proposal.rs
- full-service/src/service/transaction_builder.rs
- signer/src/service/api/mod.rs
An optional (for backwards compatibility with v1 json API) shared_secret field has been added to the service model for OutputTxo's. This enables us to re-decrypt the txo from the ledger, including its memo, at a future time when deemed necessary.
This will directly support the T3 integration by allowing authenticated sender memos of sent txos to be recorded
Unit tests
Adjusting upstream PRs to utilize the new shared_secret information if available
> Adding shared secret to output txo

- full-service/migrations/2023-11-11-154436_force_account_resync/down.sql
- full-service/migrations/2023-11-11-154436_force_account_resync/up.sql
- full-service/src/db/account.rs
- full-service/src/db/models.rs
- full-service/src/db/schema.rs
- full-service/src/json_rpc/v1/api/wallet.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/service/account.rs
- full-service/src/service/balance.rs
- full-service/src/service/sync.rs
Forcing each account in the wallet to resync with the ledger from block index 0, which will cause each one to scan txos and pick up any Authorized Sender Memos that are found.
During this sync, normal API calls will be unavailable, and an error will be returned with the current percentage completed of the sync.
> Account resyncing

- full-service/src/db/txo.rs
- full-service/src/json_rpc/v2/api/request.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/service/memo.rs
- mirror/src/private/main.rs
Updating the mirror to include validate sender memo as a whitelisted API call
Updating the validate sender memo to not require account id, as it can be derived from the txo that is being validated
> Update mirror endpoints

- Cargo.lock
- Cargo.toml
- mirror/Cargo.toml
full-service wasn't building on Macs with Apple Silicon
- update mbedtls crate revision to one that builds on Apple Silicon
- update boring create version to one that builds on Apple Silicon
- while at it, also updated mobilecoin.git submodule commit to latest commit in release/v5.2 branch, which is one commit past release v5.2.3, the latest release, with that additional post-release commit being to update the mobilecoin.git mbedtls crate revision to the same revision used in this PR.
> uprev mbedtls and boring to build on apple silicon

- full-service/src/json_rpc/v2/models/tx_proposal.rs
Callers can benefit from having easy access to TxOut public keys since that is often a common method for checking if a TxOut has been included in the ledger.
> add the txo public key to a few api response structs

- tools/build-fs.sh
Previously there was a command substitution '`cargo check`' in the help
message for `tools/build-fs.sh`. This resulted in `cargo check` being
executed when the help message was printed. Now single quotes are used
around the 'cargo check' text to separate it from the rest of the text
in the help message.
> Remove command substitution in help message

- .github/workflows/ci.yml
- .github/workflows/release.yml
ci workflows not being picked up by any runner.
changed ci and release workflows from using runs-on: [self-hosted, Linux, large] to runs-on: mco-dev-large-x64
> update ci and release workflows to use mco-dev-large-x64 runners

- .internal-ci/docker/Dockerfile.full-service
- .internal-ci/docker/Dockerfile.full-service-with-build
Added libusb-1.0 and libdbus-1-3 apt packages to the full-service docker image's runtime environment. These are needed to provide the shared objects linked at build time with the full-service executables in order to support hardware signing devices. The executables will not run without them being present.
> add libusb-1.0 and libdbus-1-3 dynlibs to docker image runtime

- python/tests/test_client.py
python integration tests fails API v2 `test_network_status_fees` on mainnet because mainnet lacks FauxUSD token.
* update `test_network_status_fees` to not require fees be set for FauxUSD
> update test_network_status_fees to work on mainnet and testnet

- full-service/src/json_rpc/v1/models/tx_proposal.rs
full-service should closely track the mobilecoin core v6.0 release work as there is need to release compatible full-service *in advance* of core v6.0 deployments due to breaking changes (DCAP attestation) that will prevent previous versions of full-service from working with core v6
* update mobilecoin.git submodule to latest release/v6.0 commits
* update ledger-mob submodule to also incorporate latest release/v6.0 commits
* update use of mc_mobilecoind::payments::OutlayV2 to specify new tx_private_key struct member
> track change to mobilecoin release/v6.0 and OutlayV2 struct

- .github/workflows/refresh-ledger.yaml
refresh-ledger github action workflow failing because of libraries missing in container
install libdbus-1-3 and libusb-1.0-0 before running full-service.
> Fix refresh ledger

- Cargo.lock
- full-service/src/json_rpc/v1/models/tx_proposal.rs
The 6.0 release branch of the mobilecoin.git core repo, on top of which full-service is currently being built, contains a breaking change to the mobilecoind::UnspentTxOut function.  This PR updates full-service to be compatible.
> Update function parameters when calling mobilecoind::UnspentTxOut

- full-service/src/json_rpc/v2/api/wallet.rs
In order to keep a `view-only `account's balances in sync with activity happening on the account outside of this instance of full-service, one can:
- use `create_view_only_account_sync_request ` to obtain a list of txos for which the `view-only` account does not know the corresponding key images
- process the resulting txo_sync_request using software that has access to the account's private keys, producing a `sync_view_only_account` request that associates `tx_out_public_keys` with their corresponding `key_images`, and
- submit the `sync_view_only_account` request to the full-service with the `view-only` account.
The `txo_sync_request` generated in response to the `create_view_only_account_sync_request` method is supposed to include the account_id of the `view-only` account.  This helps …
> convert hex encloded account_id to AccountId instead of using zeros

- t3/api/proto/t3/admin/v1/api_key_service.proto
- t3/api/proto/t3/admin/v1/migration_service.proto
- t3/api/proto/t3/v1/t3.proto
* updated t3/api/proto/... to use latest t3 api protos.
> updates to t3 API protobufs

- Cargo.lock
The mobilecoin submodule contains a fix to serializing the `subaddress` index of a `TxoUnsync` struct, which is need to fix full-service's response to the `create_view_only_account_sync_request` API method.
* update the mobilecoin submodule to the latest release/v6.0 commit, which includes the fix.
* update the ledger-mob submodule to match
> uprev mobilecoin and ledger-mob

- full-service/src/db/transaction_log.rs
Added rust unit tests to confirm the new method of `transaction_log_id` generation for vectors of `OutputTxos` passed to the `TryFrom<Vec<OutputTxo>>`  implementation for `TransactionId`.
There are two new unit tests added:
1. `test_try_from_vec_output_txo_for_transaction_id`
2. `test_try_from_empty_vec_output_txo_for_transaction_id`
The first test creates different sized vectors of `OutputTxo` structures.  The vectors are of size 1 through 10.  The embedded `TxOut` structs are initialized from entropy, so the public keys are unique on each run.  Each vector is first scanned for its minimum public key.  The vector is then passed to `TransactionId::try_from()` and the resulting `transaction_log_id` is asserted to be equal to the vector's minimum public key.
The second test checks that the …
> Unit tests for FS-154 New TransactionId Derivation

- full-service/src/json_rpc/v1/e2e_tests/transaction/build_submit/build_and_submit.rs
- full-service/src/json_rpc/v1/e2e_tests/transaction/build_submit/build_then_submit.rs
- full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/build_and_submit.rs
- full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/build_then_submit.rs
- full-service/src/service/receipt.rs
- full-service/src/service/transaction_builder.rs
Block production rate on mainnet has increased.  Previously, full-service used a default of setting the tombstone block 10 blocks in the future. This is now causing a lot of tombstone block exceeded errors.
* set the default tombstone block to 100 blocks in the future. This matches the current setting for fog.
> increase default valid block window for new tx to 100

- full-service/src/db/transaction_log.rs
- full-service/src/db/txo.rs
- full-service/src/service/sync.rs
Previously when syncing multiple accounts the first account synced would
fail expired transaction logs from other accounts. This would result in
failing transaction logs that may have actually succeeded. Now only
expired transaction logs for the currently processing account will be
failed.
> Only fail transaction logs for specified account.

- .github/actions/build-publish-docker/action.yaml
- .github/actions/build-rust/action.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/on-tag.yaml
Refactor the "release on tag" process.  Clean up and simplify the process.  Build binaries, package up and publish results and Generate a draft GitHub Release.
Change build-rust to use cache module for built binaries, but change the zip artifacts attached to the action from directories to the tarballs with permissions preserved, ready to attach to the Github Release.  
Just a note on why I'm using this pattern: Yes its a bit silly to zip a tar.gz file, but zip files are what GH uses for their actions artifacts. For some reason when you use the GH action to restore an artifact they remove the executable permissions from any files in the zip. I don't really understand why this is since the permissions are preserved if I download the same zip locally.
The release step includes boilerplate …
> CI/CD Refactor - Release Process

- .github/workflows/on-tag.yaml
Add GitHub actions permission for on-tag so we can create a release.
> add contents: write permission so we can create a release

- python/mobilecoin/cli.py
python CLI used on mainnet was getting a fatal error when used with the `status` command due to trying to display fees for token 8192, which is testnet only.
* when iterating over the defined tokens in order to display their minimum fees, only try and display fees for tokens that are present in the fee map.
> python cli status cmd should only display fees for tokens on chain

- full-service/src/service/balance.rs
PR #1013 notes that the python CLI reports the wallet sync status incorrectly under conditions where accounts exist in the `wallet_db` that have sync status ahead of the `ledger_db`'s sync status.
This can happen either when:
1.  importing an account who's `first_block_index` is ahead of the local `ledger_db`'s `local_block_height`, or
2.  when the local `ledger_db` is lost, full-service is resync'ing it from the network, and has not yet caught up to where the  accounts in the `wallet_db` were previously synced.
#1013 proposes a fix for the issue by changing the CLI `status` command to report `local_block_height` instead of `min_synced_block_index`.
This PR proposes an alternate approach where instead we fix the calculation of `min_synced_block_index` so that it is the minimum of …
> calculate min_synced_block_index using local_block_height

- .devcontainer.json
Add a devcontainer config.  This will allow IDEs like VScode to automatically use a containerized environment for all their features.
> add devcontainer config

- full-service/src/service/sync.rs
Previously over 90 lines was duplicated in `sync_account_next_chunk()`
between regular accounts and view only accounts. This logic has now been
consolidated such that only the minor differences have been
consolidated.
> Consolidate logic for `sync_account_next_chunk()`

- full-service/src/db/transaction_log.rs
- full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/build_then_submit.rs
- full-service/src/service/sync.rs
Previously `transaction_log`s were marked successful if the input TXO(s)
were spent according to the block chain. This was problematic when
multiple `transaction_log`s were created that utilized the same input
TXOs. These `transaction_log`s using the same input TXOs could happen
when two clients were talking to the same Full-Service instance and
those clients were using two step build and submit:
1. Client_a sends `build_transaction`, input TXO_n is used
2. Client_b sends `build_transaction`, input TXO_n is also used
3. Client_a `submit_transaction`
4. Client_b `submit_transaction` before the block chain knows that the
Client_a transaction exists and will consume `TXO_n`. The blockchain
will still reject this transaction eventually.
5. Previously, Full-Service would see that input TXO_n …
> Fix transaction logs incorrectly marked successful

- full-service/src/db/transaction_log.rs
- full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/build_then_submit.rs
- full-service/src/service/sync.rs
Previously a transaction log would need to wait for the tombstone block
to occur. Now when an input txo is spent any transaction logs that
haven't been finalized and use that input txo will be marked failed.
> Fail transaction logs when input txos are consumed

- .github/workflows/on-tag.yaml
* fixes a small typo in a path causing the github release part of the on-tag workflow to fail.
> fix typo in on-tag github action

- .devcontainer.json
- .github/actions/test-python-integration/action.yaml
- .github/workflows/on-pr.yaml
- .internal-ci/docker/Dockerfile.full-service
- .internal-ci/docker/entrypoints/full-service.sh
- .internal-ci/helm/full-service/templates/full-service-service.yaml
- .internal-ci/helm/full-service/templates/full-service-statefulSet.yaml
- .internal-ci/util/wait-for-full-service.sh
- python/mobilecoin/cli.py
- python/tests/conftest.py
- python/tests/test_client.py
- python/tests/test_client_v1.py
- tools/.shared-functions.sh
- tools/run-fs.sh
- tools/test-python-integration.sh
Create a wrapper around the python integration tests to make funding running tests easier.
- ./tools/test-python-integration.sh - wrapper to setup, fund, run and return leftover funds.
- Improve some outputs for the mob full-service cli tool.
- 'balance' command for easier to parse balance output
- 'export' command now accepts a flag for file name and path to save export json.
- 'list' accepts optional flag to output a single account
- Reduce funds required for test runs.
- Test runs now transfer 0.001 MOB
- Funding request is 0.02.  reduces the amount of lost mob if something goes wrong and clean up steps cannot complete.
- Create and fund new wallets for each test runs.  The old saved wallets took over 30s to sync.  Tests would timeout and fail while waiting for sync to complete.
- Fund …
> enable python integration tests.

- .devcontainer.json
- .github/actions/bootstrap-macos/action.yaml
- .github/actions/build-rust/action.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/on-tag.yaml
Add process to MacOS build to sign binaries and submit the results to the notary. This should allow the cli executables to run with just the "You have downloaded this from the web" warning instead of the "We can't verify this - go☠️" error.
> Add MacOS signing and notary

- .github/workflows/on-pr.yaml
- full-service/src/db/account.rs
- full-service/src/db/txo.rs
- full-service/src/json_rpc/v1/api/test_utils.rs
- full-service/src/json_rpc/v2/api/test_utils.rs
- full-service/src/service/account.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/test_utils.rs
This PR fixes a bug that prevents the fog hint from being properly created when adding change outputs.
Prior to this fix, the change output would not get a fog hint even for fog-enabled accounts.
* Fixes the aforementioned bug
The fix is not particularly elegant, see comments in code.
Added unit tests that ensure correct fog hints are being generated for both the change address and recipients.
I opted to not add a unit test for ensuring no fog hint gets generated for a change address for non-fog accounts, since I don't think that's an interesting thing to test because in real life there's no public key available for encrypting the fog hint if the account does not have fog enabled. Adding that test would just be a lot of copy-paste and it doesn't seem worth the code bloat to me.
I also …
> fix a bug that prevented change output fog hint from being properly created

- Cargo.lock
- full-service/Cargo.toml
- full-service/src/json_rpc/v2/api/request.rs
- full-service/src/json_rpc/v2/api/response.rs
- full-service/src/json_rpc/v2/api/wallet.rs
- full-service/src/json_rpc/v2/models/mod.rs
- full-service/src/json_rpc/v2/models/signed_contingent_input.rs
- full-service/src/service/confirmation_number.rs
- full-service/src/service/mod.rs
- full-service/src/service/signed_contingent_input.rs
- full-service/src/test_utils.rs
We want a way for users to prove they are in possession of specific TxOuts that are unspent. For a proof of reserve, we want to be able to reveal the following about a TxOut in a verifiable way:
1. The amount of the TxOut
2. The fact that the user constructing the proof is able to spend the TxOut
3. The key image of the TxOut, which lets us know whether it has been spent or not.
A valid Signed Contingent Input (e.g. one that has a valid MLSAG signature and contains a TxOut that appears in the ledger) is one possible way to provide such a proof. An SCI is constructed such that it has a ring size of 1 and is made unspendable (due to tombstone block limit or a required output that can never be satisfied, e.g. u64::MAX) allows us to achieve the 3 goals mentioned above.
We need the ability for …
> Validate proof of reserve SCI

- full-service/src/json_rpc/v2/api/response.rs
- full-service/src/json_rpc/v2/models/signed_contingent_input.rs
@nick-mobilecoin reminded me that I can use `#[serde(flatten)]` to simplify the result returned from the `validate_proof_of_reserve_sci` API call.
After this change, the response looks like this:
```
{
"method": "validate_proof_of_reserve_sci",
"result": {
"status": "valid",
"tx_out_public_key": "d6c9f4eeb819db2d6e5f28098fd9a2ceda42a06efe6c4707c761ff8a57e10508",
"key_image": "6e1e88d267ab9914faa9ff7ff838eef4d9ac5a00727e67ebf69c64e0deac6367",
"amount": {
"value": "5555155555555",
"token_id": "0"
}
},
"jsonrpc": "2.0",
"id": 1
}
```
Which i nicer.
Small changes to the response type for the `validate_proof_of_reserve_sci` method.
> Cleanup validate_proof_of_reserve_sci result

- .github/actions/bootstrap-macos/action.yaml
- .github/workflows/on-pr.yaml
- Brewfile
- full-service/src/db/txo.rs
- full-service/src/service/balance.rs
The get_account_status method is
1. adding together the secreted txo balances across token_ids
2. reporting that same, blended balance repeatedly under each token_id’s block in the response
Instead, it should report a separate secreted total amount for each token_id as that token_id’s secreted balance.
It especially doesn’t make sense to sum this quantity across token_ids as the amounts are in native units for each token_id, which differs from token_id to token_id.
* add optional `token_id` parameter to `list_secreted` txo lookup
* pass through the `token_id` from functions calling `list_secreted` as appropriate
* update `test_received_txo_lifecycle` detect regression
1. updated `db::txo::tests::test_received_txo_lifecycle` test as per above
2. did test on prod build on account with both …
> (SENTZ-3883) fix get_account_status to calculate secreted balance per-token_id

- .github/actions/build-rust/action.yaml
- .github/actions/download-sigstruct/action.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/on-tag.yaml
- tools/.shared-functions.sh
- tools/build-fs.sh
Full-service relies on the `production.json` file for location of enclave measurements it should use as part of its build. We should use and pint to the versioned production file instead of assuming that latest is correct.
* Add logic to download the versioned copy of the enclave measurements.
* fix tools/build-fs.sh
* fix gha workflows
> pin enclave measurements download version

- .github/actions/bootstrap-macos/action.yaml
- .github/workflows/on-pr.yaml
- .github/workflows/on-tag.yaml
- tools/test.sh
tools/test.sh, the script for locally running unit and integration tests, needs an update to work with the current tools/.shared-functions.sh, providing it the version of the measurements that are to be downloaded.
* update tools/test.sh to pass the version number of enclave measurements to download back to .shared-functions.sh's `get_css_file`. .shared-functions.sh now reads the version string to use out of the environment variable ENCLAVE_RELEASE_TAG and falls back to a hard-coded default version, currently v6.0.0, and this needs to be explicitly passed to `get_css_file`
This is a companion to merged PR #1049
> update tools/test.sh to use version pinned enclave measurements

- full-service/src/service/models/transaction_memo.rs
- full-service/src/service/transaction_builder.rs
- full-service/src/test_utils.rs
The purpose of this PR is to break the dependency`TransactionMemo` currently have on `AccountKey`, and instead replace it with a generic credentials enum (`TransactionMemoSignerCredentials`).
The main reason to do this is that it enables us to add a hardware wallet as the signer, which we do in a followup PR.
> Rework TransactionMemo to support various types of credentials
